/**
 * MojoMotor - by EllisLab
 *
 * @package		MojoMotor
 * @author		MojoMotor Dev Team
 * @copyright	Copyright (c) 2003 - 2011, EllisLab, Inc.
 * @license		http://mojomotor.com/user_guide/license.html
 * @link		http://mojomotor.com
 * @since		Version 1.0
 * @filesource
 */

/*
		http://mojomotor.com/user_guide/license.html
 @link		http://mojomotor.com
 @since		Version 1.0
 @filesource
*/
if(typeof console=="undefined"||!console.log)console={log:function(){return false}};jQuery.ajaxSetup({cache:true});update_edit_mode_callback=function(a){Mojo.edit_mode=a};mojoEditor={revealed_page:"",breadcrumb_object:{},is_open:true,last_active_menu:"",active_menu:"",region_type:"local",mojo_editor_ref:"",follow_link:true};$(window).resize(function(){$("#mojo-container").width($(this).width())});
mojoEditor.setup_mojobars=function(a){jQuery.address.init(function(){jQuery.address.strict(false)}).change(function(b){if(b.path!="")mojoEditor.follow_link||mojoEditor.reveal_page(b.path)});jQuery("head").append('<link type="text/css" rel="stylesheet" href="'+Mojo.URL.css_path+'/jqueryui" />\n<link type="text/css" rel="stylesheet" href="'+Mojo.URL.css_path+'" />');Mojo.Vars.additional_css!=""&&jQuery("head").append('<link type="text/css" rel="stylesheet" href="'+Mojo.Vars.additional_css+'" />\n');
if(Mojo.Vars.bar_state==false){mojoEditor.is_open=false;bar_position="-77px"}else{mojoEditor.is_open=true;bar_position="0px"}jQuery("body").prepend('<div id="MojoMotorContentPusher" style="height:77px;margin-top:'+bar_position+';"></div>');jQuery.modal(a,{overlayId:"mojo_editor_overlay",containerId:"mojo-container",maxHeight:77,containerCss:{top:bar_position,left:0,width:"100%"},close:false,focus:false,autoResize:false,autoPosition:false,onOpen:function(b){b.container.slideDown("fast",function(){b.data.show()})},
onClose:function(b){b.container.slideUp("fast")}});reveal_page=jQuery('<p id="mojo_reveal_page_notice"></p><div id="mojo_breadcrumbs"><div id="mojo_ajax_page_loader"><img src="{cp_img_path}ajax-loader_dark.gif" alt="" height="24" width="24" /></div><a href="#" id="mojo_reveal_page_back" class="mojo_sub_page"></a><span id="mojo_reveal_current_page"></span></div><div id="mojo_reveal_page"><div id="mojo_reveal_page_content"></div></div><a href="#" class="mojo_reveal_page_close">'+Mojo.Lang.close+"</a>").css({overflow:"auto",
"max-height":jQuery(window).height()-150+"px"});jQuery("#mojo-container").append(reveal_page);jQuery(reveal_page).hide();jQuery(".mojo_reveal_page_close").css({left:jQuery(document).width()/2-15+"px"});jQuery(".mojo_reveal_page_close").click(function(b){b.preventDefault();mojoEditor.unreveal_page()});mojoEditor.collapse_bar();mojoEditor.setup_logout();jQuery("#mojo-container").delegate(".mojo_page_refresh_trigger","click",function(){window.location.reload()});jQuery("#mojo-container").delegate("#mojo_main_bar li a, .mojo_sub_page",
"click",function(b){b.preventDefault();mojoEditor.follow_link=true;mojoEditor.last_active_menu=mojoEditor.active_menu;mojoEditor.active_menu=jQuery(this).parent().attr("id");if(mojoEditor.active_menu=="")mojoEditor.active_menu=mojoEditor.last_active_menu;if(jQuery("#mojo_reveal_page").is(":visible")===false||mojoEditor.revealed_page!=jQuery(this).attr("href")){mojoEditor.revealed_page=jQuery(this).attr("href");if(jQuery(this).hasClass("mojo_sub_page")&&!jQuery(this).hasClass("mojo_breadcrumb_supress"))mojoEditor.breadcrumb_object.seg_method=
jQuery(this).attr("title");else{jQuery(this).hasClass("mojo_breadcrumb_supress")&&mojoEditor.active_page(true);mojoEditor.breadcrumb_object.seg_controller=[jQuery(this).attr("title"),jQuery(this).attr("href")];mojoEditor.breadcrumb_object.seg_method=""}mojoEditor.reveal_page(mojoEditor.revealed_page)}else jQuery(this).hasClass("mojo_sub_page")&&!jQuery(this).hasClass("mojo_breadcrumb_supress")||mojoEditor.unreveal_page()});jQuery("#mojo-container").delegate("#layout_name","keyup",function(){mojoEditor.liveUrlTitle(this)});
jQuery("#mojo-container").delegate("#page_title","keyup",function(){jQuery("input[name=page_id]").length||mojoEditor.liveUrlTitle(this,"url_title")});jQuery.getScript(Mojo.URL.site_path+"/javascript/load_ckeditor",function(){mojoEditor.is_open&&mojoEditor.enable_page_regions()});jQuery.getScript(Mojo.URL.editor_plugin_path)};
mojoEditor.collapse_bar=function(){collapse_tab=jQuery('<div id="collapse_tab"></div>');jQuery("#mojo-container").append(collapse_tab);Mojo.Vars.bar_state==true&&jQuery(collapse_tab).hide();jQuery("#mojo_bar_view_mode, #collapse_tab").click(function(){if(mojoEditor.is_open){mojoEditor.disable_page_region();jQuery(reveal_page).slideUp("fast");jQuery("#collapse_tab").slideDown("fast");jQuery("#MojoMotorContentPusher").animate({"margin-top":"-77px"});jQuery("#mojo-container").animate({top:"-"+jQuery("#mojo-container").height()});
mojoEditor.is_open=false}else{mojoEditor.enable_page_regions();jQuery("#MojoMotorContentPusher").animate({"margin-top":0});jQuery("#mojo-container").animate({top:0},function(){jQuery("#collapse_tab").slideUp("fast")});mojoEditor.is_open=true}jQuery.ajax({type:"POST",data:Mojo.Vars.csrf_token+"="+Mojo.Vars.csrf,url:Mojo.URL.admin_path+"/editor/bar_state/"+mojoEditor.is_open})})};
mojoEditor.enable_page_regions=function(){jQuery(".mojo_page_region").each(function(){var a=jQuery(this).attr("id").replace("_"," ");mod_editable_layer=jQuery("<div class='mojo_editable_layer'></div>").css({opacity:"0.4",width:jQuery(this).width(),height:jQuery(this).outerHeight()}).fadeIn("fast");jQuery(this).prepend(jQuery("<div class='mojo_editable_layer_header'><p>"+Mojo.Lang.local+" : "+a+"</p></div>")).prepend(mod_editable_layer)});jQuery(".mojo_global_region").each(function(){var a=jQuery(this).attr("id").replace("_",
" "),b=jQuery(this).attr("data-mojo_id");b=b!=undefined&&Mojo.Vars.layout_id!=b?Mojo.Lang.super_global:Mojo.Lang.global;mod_editable_layer=jQuery("<div class='mojo_editable_layer mojo_global'></div>").css({opacity:"0.4",width:jQuery(this).width(),height:jQuery(this).outerHeight()+20}).fadeIn("fast");jQuery(this).prepend(jQuery("<div class='mojo_editable_layer_header'><p>"+b+" : "+a+"</p></div>")).prepend(mod_editable_layer)});jQuery(".mojo_editable_layer, .mojo_editable_layer_header").click(function(){mojoEditor.init_editor(jQuery(this).parent())})};
mojoEditor.upload_result=function(a,b){var f,c;c=CKEDITOR.dialog.getCurrent();if(c.getName()=="image"){c.selectPage("info");f=c.getContentElement("info","txtUrl");c=c.getContentElement("info","txtAlt");f&&f.setValue(a);c&&c.setValue(b)}};mojoEditor.disable_page_region=function(){jQuery(".mojo_editable_layer_header, .mojo_editable_layer").fadeOut("fast",function(){jQuery(this).remove()})};
mojoEditor.init_editor=function(a){a=jQuery(a);region_id=a.attr("id");region_layout_id=a.attr("data-mojo_id");mojoEditor.region_type=a.hasClass("mojo_global_region")?"global":"local";jQuery(".mojo_editable_layer_header, .mojo_editable_layer").remove();mojoEditor.mojo_editor_ref==""&&CKEDITOR.on("dialogDefinition",function(b){var f=b.data.name;b=b.data.definition;b.onLoad=function(){Mojo.Vars.show_expanded_image_options||jQuery(".mojopreview").hide()};if(f=="image"){b.removeContents("advanced");b.removeContents("Link");
b.removeContents("image");if(!Mojo.Vars.show_expanded_image_options){infoTab=b.getContents("info");infoTab.remove("txtBorder");infoTab.remove("txtHSpace");infoTab.remove("txtVSpace");infoTab.remove("cmbAlign")}}else if(f=="link"){b.removeContents("advanced");b.removeContents("upload");infoTab=b.getContents("info");infoTab.remove("linkType");infoTab.remove("browse");infoTab.add({type:"html",id:"noAnchors",style:"margin: 15px 0;",html:"<p>"+Mojo.Lang.or+"</p>"});infoTab.add({type:"select",label:Mojo.Lang.or_choose_page,
id:"link",items:[],onLoad:function(){var c=this;c.add(Mojo.Lang.or_choose_page_dropdown,"0");jQuery.ajax({type:"POST",dataType:"json",url:Mojo.URL.admin_path+"/editor/list_pages/",success:function(g){jQuery.each(g,function(d,h){c.add(h.page_title,h.url_title)})}})},onChange:function(){if(this.getValue()!=""&&this.getValue()!==0){var c=CKEDITOR.dialog.getCurrent();if(c!==null){c.setValueOf("info","url",Mojo.URL.site_path+"/"+this.getValue());c.setValueOf("info","protocol","http://")}}}});infoTab.add({type:"checkbox",
id:"targeta",label:Mojo.Lang.open_in_new_window,style:"margin-top: 15px;",commit:function(){var c=CKEDITOR.dialog.getCurrent();if(c!==null)this.getValue()?c.setValueOf("target","linkTargetType","_blank"):c.setValueOf("target","linkTargetType","notSet")}})}});mojoEditor.original_contents=a.html();a.wrapInner('<div id="mojo-active-edit"></div>');mojoEditor.mojo_editor_ref=jQuery("#mojo-active-edit").ckeditor(function(){},{skin:"mojo,"+Mojo.URL.editor_skin_path,language:"en",startupMode:Mojo.edit_mode,
toolbar:Mojo.toolbar,extraPlugins:"mojo_cancel,mojo_save",removePlugins:"scayt,bidi,iframe,save",toolbarCanCollapse:false,toolbarStartupExpanded:true,resize_enabled:true,width:a.width()<128?128:a.width(),height:a.height()+20,minHeight:80,dialog_backgroundCoverColor:"#5C5C5C",dialog_backgroundCoverOpacity:0.8,linkShowTargetTab:false,filebrowserBrowseUrl:Mojo.URL.admin_path+"/editor/browse/",filebrowserWindowWidth:"780",filebrowserWindowHeight:"500",filebrowserUploadUrl:Mojo.URL.admin_path+"/editor/upload/"},
jQuery("#mojo-active-edit").html());mojoEditor.mojo_editor_ref.data("ckeditorInstance").on("afterCommandExec",function(b){if(b&&b.data&&b.data.name&&b.data.name=="maximize"){$("html").css("overflow","");$("#mojo-container").css("z-index","")}})};mojoEditor.remove_editor=function(a){if(a){a.getCommand("maximize").state===1&&a.execCommand("maximize");a.destroy();mojoEditor.is_open&&mojoEditor.enable_page_regions()}};
mojoEditor.setup_logout=function(){jQuery("#mojo_logout").click(function(a){a.preventDefault();a={};a.Cancel=function(){jQuery(this).dialog("close")};a[Mojo.Lang.logout]=function(){jQuery.post(Mojo.URL.site_path+"/login/logout",function(){jQuery.modal.close();window.location=Mojo.URL.site_path});jQuery(this).dialog("close")};jQuery("<p>"+Mojo.Lang.logout_confirm+"</p>").dialog({resizable:false,title:Mojo.Lang.logout,modal:true,position:["center",110],buttons:a})})};
mojoEditor.delete_abstraction=function(a){jQuery("#mojo-container").delegate(".mojo_"+a,"click",function(b){b.preventDefault();var f=jQuery(this).attr("href");b=Mojo.Lang[a];var c="";if(a=="page_delete")if(jQuery(this).closest("li").find("li").length>0)c+='<p class="error">'+Mojo.Lang.subpage_delete+"</p>";if((a=="layout_delete"||a=="page_delete")&&jQuery(".mojo_"+a).length==1)c+='<p class="error">'+Mojo.Lang.last_item_delete+"</p>";var g={};g.Cancel=function(){jQuery(".mojo_"+a+"_dialog").dialog("close")};
g[b]=function(){jQuery.ajax({type:"POST",url:f,data:Mojo.Vars.csrf_token+"="+Mojo.Vars.csrf+"&confirmed=true",dataType:"json",success:function(d){d.result=="success"&&jQuery("#mojo_"+a+"_"+d.id).slideUp(function(){jQuery(this).remove();a=="page_delete"&&mojoEditor.send_site_structure()});jQuery(".mojo_"+a+"_dialog").dialog("close");mojoEditor.add_notice(d.message,d.result)}})};jQuery("<div class='mojo_"+a+"_dialog'><p>"+jQuery(this).attr("title")+"</p>"+c+"</div>").dialog({resizable:false,title:b,
modal:true,width:"400px",buttons:g})})};
mojoEditor.subpage_reinit=function(){jQuery("#mojo_reveal_page_content form").length>0&&jQuery("#mojo_reveal_page_content form input:visible").eq(0).focus();jQuery("textarea.mojo_textbox").length&&jQuery.getScript(Mojo.URL.js_path+"/plugin/tabby",function(){jQuery("textarea.mojo_textbox").tabby()});if(jQuery("#mojo_site_structure").length){mojoEditor.update_page_hierarchy();jQuery("#mojo_site_structure li").draggable({handle:" > div",opacity:0.75,helper:"clone"});jQuery("#mojo_site_structure div, .mojo_site_structure_placeholder").droppable({accept:"#mojo_site_structure li",
tolerance:"pointer",drop:function(a,b){var f=jQuery(this).parent(),c=!jQuery(this).hasClass("mojo_site_structure_placeholder");c&&f.children("ul").length===0&&f.append("<ul />");c?f.children("ul").prepend(b.draggable):f.after(b.draggable);f.find("div.ie_fix").removeClass("ie_fix_hover");f.find(".mojo_site_structure_placeholder").css({visibility:"hidden",opacity:"0",height:"10px"});mojoEditor.send_site_structure()},over:function(){jQuery(this).filter("div.ie_fix").addClass("ie_fix_hover");jQuery(this).filter(".mojo_site_structure_placeholder").css({visibility:"visible",
opacity:"1",height:"29px"})},out:function(){jQuery(this).filter("div.ie_fix").removeClass("ie_fix_hover");jQuery(this).filter(".mojo_site_structure_placeholder").css({visibility:"hidden",opacity:"0",height:"10px"})}});mojoEditor.pages_line_tree()}};
mojoEditor.pages_line_tree=function(){jQuery("#mojo_site_structure li").css({background:"none"});jQuery("#mojo_site_structure ul > li").css({background:"url({cp_img_path}page_line_child_single.png) no-repeat left top"});jQuery("#mojo_site_structure > li").has("ul li").css({background:"url({cp_img_path}page_line_parent_children.png) no-repeat left top"});jQuery("#mojo_site_structure ul li").has("ul li").css({background:"url({cp_img_path}page_line_child_children.png) no-repeat left top"});jQuery("#mojo_site_structure ul").each(function(){jQuery(this).children("li:last").css({background:"#202020 url({cp_img_path}page_line_child_last.jpg) no-repeat left top"})});
jQuery("#mojo_site_structure ul li:last-child").has("ul li").css({background:"url({cp_img_path}page_line_sublast_children.png) no-repeat left top"})};mojoEditor.active_page=function(a){if(a){jQuery("#mojo_main_bar li").removeClass();mojoEditor.active_menu=""}else if(mojoEditor.last_active_menu!=mojoEditor.active_menu&&mojoEditor.active_menu!=""){jQuery("#mojo_main_bar li").removeClass();jQuery("#mojo-container #"+mojoEditor.active_menu).addClass(mojoEditor.active_menu+"_active")}};
mojoEditor.reveal_page=function(a,b){if(typeof b=="undefined")b=true;jQuery("#mojo_ajax_page_loader").fadeIn("fast");jQuery("body").css({cursor:"wait"});mojoEditor.active_page();jQuery.address.value(a);jQuery("#mojo_reveal_page_content").load(a,function(){jQuery("#mojo_ajax_page_loader").hide();jQuery(".mojo_reveal_page_close").show();jQuery("body").css({cursor:"default"});jQuery("#mojo_reveal_page_content form").submit(function(f){f.preventDefault();mojoEditor.follow_link=true;jQuery.ajax({type:"POST",
url:jQuery(this).attr("action"),data:jQuery(this).serialize(),dataType:"json",success:function(c){c.message!==undefined&&c.result!==undefined&&mojoEditor.add_notice(c.message,c.result);if(c.reveal_page!==undefined){mojoEditor.breadcrumb_object.seg_method="";jQuery("#mojo_reveal_current_page").hide();mojoEditor.revealed_page=c.reveal_page;mojoEditor.reveal_page(c.reveal_page,false)}if(c.callback!==undefined){args=c.callback_args!==undefined?c.callback_args:"";window[c.callback](args)}}})});jQuery(reveal_page).slideDown("fast",
function(){mojoEditor.breadcrumbs()});mojoEditor.subpage_reinit()});b===true&&mojoEditor.remove_notice();mojoEditor.follow_link=false};mojoEditor.unreveal_page=function(){mojoEditor.remove_notice();mojoEditor.active_page(true);jQuery("#mojo_breadcrumbs").slideUp("fast");jQuery("#mojo_reveal_page").slideUp("fast");jQuery(".mojo_reveal_page_close").hide();mojoEditor.follow_link=false};
mojoEditor.add_notice=function(a,b){if(typeof b=="undefined")b="notice";jQuery("#mojo_reveal_page_notice").html(a);jQuery("#mojo_reveal_page_notice").attr("class",b);jQuery("#mojo_reveal_page_notice").css({visibility:"visible","margin-left":"-"+jQuery("#mojo_reveal_page_notice").outerWidth()/2+"px"});jQuery("#mojo_reveal_page_notice").hide().fadeIn("fast")};mojoEditor.remove_notice=function(){jQuery("#mojo_reveal_page_notice").fadeOut("fast",function(){jQuery(this).css({visibility:"hidden"})})};
mojoEditor.breadcrumbs=function(){jQuery("#mojo_reveal_page_back").hide();jQuery("#mojo_reveal_current_page").hide();jQuery("#mojo_reveal_page_back").html(mojoEditor.breadcrumb_object.seg_controller[0]).show();jQuery("#mojo_reveal_page_back").attr("href",mojoEditor.breadcrumb_object.seg_controller[1]);mojoEditor.breadcrumb_object.seg_method!=""&&jQuery("#mojo_reveal_current_page").html(mojoEditor.breadcrumb_object.seg_method).show()};
mojoEditor.update_page_hierarchy=function(){jQuery(".mojo_add_page_inline").each(function(){var a="";jQuery(this).parents("li").each(function(){a=jQuery(this).attr("id").substring(17)+"/"+a});var b=jQuery(this).attr("href").substring(0,jQuery(this).attr("href").indexOf("add")+3);jQuery(this).attr("href",b+"/"+a)})};
mojoEditor.send_site_structure=function(){jQuery.ajax({type:"POST",url:Mojo.URL.admin_path+"/pages/page_reorder/",data:Mojo.Vars.csrf_token+"="+Mojo.Vars.csrf+"&"+jQuery("#mojo_site_structure").serializeTree("site_structure",".ui-draggable-dragging"),dataType:"json",success:function(a){mojoEditor.add_notice(a.message,a.result);mojoEditor.update_page_hierarchy();mojoEditor.pages_line_tree()}})};
mojoEditor.liveUrlTitle=function(a,b){for(var f=jQuery(a).getCaretPos(),c=jQuery(a).val().toLowerCase(),g=Mojo.URL.separator,d="",h=0;h<c.length;h++){var e=c.charCodeAt(h);if(e>=32&&e<128)d+=c.charAt(h);else if(e=="223")d+="ss";else if(e=="224")d+="a";else if(e=="225")d+="a";else if(e=="226")d+="a";else if(e=="229")d+="a";else if(e=="227")d+="ae";else if(e=="230")d+="ae";else if(e=="228")d+="ae";else if(e=="231")d+="c";else if(e=="232")d+="e";else if(e=="233")d+="e";else if(e=="234")d+="e";else if(e==
"235")d+="e";else if(e=="236")d+="i";else if(e=="237")d+="i";else if(e=="238")d+="i";else if(e=="239")d+="i";else if(e=="241")d+="n";else if(e=="242")d+="o";else if(e=="243")d+="o";else if(e=="244")d+="o";else if(e=="245")d+="o";else if(e=="246")d+="oe";else if(e=="249")d+="u";else if(e=="250")d+="u";else if(e=="251")d+="u";else if(e=="252")d+="ue";else if(e=="255")d+="y";else if(e=="257")d+="aa";else if(e=="269")d+="ch";else if(e=="275")d+="ee";else if(e=="291")d+="gj";else if(e=="299")d+="ii";else if(e==
"311")d+="kj";else if(e=="316")d+="lj";else if(e=="326")d+="nj";else if(e=="353")d+="sh";else if(e=="363")d+="uu";else if(e=="382")d+="zh";else if(e=="256")d+="aa";else if(e=="268")d+="ch";else if(e=="274")d+="ee";else if(e=="290")d+="gj";else if(e=="298")d+="ii";else if(e=="310")d+="kj";else if(e=="315")d+="lj";else if(e=="325")d+="nj";else if(e=="352")d+="sh";else if(e=="362")d+="uu";else if(e=="381")d+="zh"}h=RegExp(g+"{2,}","g");c=d;c=c.replace("/<(.*?)>/g","");c=c.replace(/\s+/g,g);c=c.replace(/\//g,
g);c=c.replace(/[^a-z0-9\-\._]/g,"");c=c.replace(/\+/g,g);c=c.replace(h,g);c=c.replace(/^_/g,"");c=c.replace(/^-/g,"");c=c.replace(/\./g,"");b=typeof b=="undefined"?a:jQuery("#"+b);jQuery(b).val(c);jQuery(a).setCaretPos(f)};
jQuery.fn.getCaretPos=function(){var a=this[0];if(a.selectionStart)return a.selectionStart>0?a.selectionStart:0;else if(a.createTextRange){a.focus();var b=document.selection.createRange();a=a.createTextRange();var f=a.duplicate();a.moveToBookmark(b.getBookmark());f.setEndPoint("EndToStart",a);return f.text.length}return"0"};
jQuery.fn.setCaretPos=function(a){var b=this[0];if(b.setSelectionRange){b.focus();b.setSelectionRange(a,a)}else b.createTextRange&&b.createTextRange().collapse(true).moveStart("character",a).moveEnd("character",a).select()};
jQuery.fn.serializeTree=function(a,b){var f="",c;c=b===undefined?this.children():this.children().not(b);if(c.length>0)c.each(function(){if(this.id.indexOf("drop_target")===-1){var g=jQuery(this).attr("id").substring(17),d="";if(jQuery(this).find("ul li").length>0){a+="["+g+"]";d=jQuery("ul:first",jQuery(this)).serializeTree(a,b);a=a.replace(/\[[^\]\[]*\]$/,"")}else f+="&"+a+"["+g+"]="+g;if(d!="")f+=d}});else f+="&"+a+"["+this.attr("id")+"]=";return f!=""?f:false};
