/*!
 * jQuery UI 1.8.2
 *
 * Copyright (c) 2010 AUTHORS.txt (http://jqueryui.com/about)
 * Dual licensed under the MIT (MIT-LICENSE.txt)
 * and GPL (GPL-LICENSE.txt) licenses.
 *
 * http://docs.jquery.com/UI
 */

(function(c){c.ui=c.ui||{};if(!c.ui.version){c.extend(c.ui,{version:"1.8.2",plugin:{add:function(a,b,d){a=c.ui[a].prototype;for(var g in d){a.plugins[g]=a.plugins[g]||[];a.plugins[g].push([b,d[g]])}},call:function(a,b,d){if((b=a.plugins[b])&&a.element[0].parentNode)for(var g=0;g<b.length;g++)a.options[b[g][0]]&&b[g][1].apply(a.element,d)}},contains:function(a,b){return document.compareDocumentPosition?a.compareDocumentPosition(b)&16:a!==b&&a.contains(b)},hasScroll:function(a,b){if(c(a).css("overflow")==
"hidden")return false;var d=b&&b=="left"?"scrollLeft":"scrollTop",g=false;if(a[d]>0)return true;a[d]=1;g=a[d]>0;a[d]=0;return g},isOverAxis:function(a,b,d){return a>b&&a<b+d},isOver:function(a,b,d,g,f,h){return c.ui.isOverAxis(a,d,f)&&c.ui.isOverAxis(b,g,h)},keyCode:{ALT:18,BACKSPACE:8,CAPS_LOCK:20,COMMA:188,COMMAND:91,COMMAND_LEFT:91,COMMAND_RIGHT:93,CONTROL:17,DELETE:46,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,INSERT:45,LEFT:37,MENU:93,NUMPAD_ADD:107,NUMPAD_DECIMAL:110,NUMPAD_DIVIDE:111,NUMPAD_ENTER:108,
NUMPAD_MULTIPLY:106,NUMPAD_SUBTRACT:109,PAGE_DOWN:34,PAGE_UP:33,PERIOD:190,RIGHT:39,SHIFT:16,SPACE:32,TAB:9,UP:38,WINDOWS:91}});c.fn.extend({_focus:c.fn.focus,focus:function(a,b){return typeof a==="number"?this.each(function(){var d=this;setTimeout(function(){c(d).focus();b&&b.call(d)},a)}):this._focus.apply(this,arguments)},enableSelection:function(){return this.attr("unselectable","off").css("MozUserSelect","")},disableSelection:function(){return this.attr("unselectable","on").css("MozUserSelect",
"none")},scrollParent:function(){var a;a=c.browser.msie&&/(static|relative)/.test(this.css("position"))||/absolute/.test(this.css("position"))?this.parents().filter(function(){return/(relative|absolute|fixed)/.test(c.curCSS(this,"position",1))&&/(auto|scroll)/.test(c.curCSS(this,"overflow",1)+c.curCSS(this,"overflow-y",1)+c.curCSS(this,"overflow-x",1))}).eq(0):this.parents().filter(function(){return/(auto|scroll)/.test(c.curCSS(this,"overflow",1)+c.curCSS(this,"overflow-y",1)+c.curCSS(this,"overflow-x",
1))}).eq(0);return/fixed/.test(this.css("position"))||!a.length?c(document):a},zIndex:function(a){if(a!==undefined)return this.css("zIndex",a);if(this.length){a=c(this[0]);for(var b;a.length&&a[0]!==document;){b=a.css("position");if(b=="absolute"||b=="relative"||b=="fixed"){b=parseInt(a.css("zIndex"));if(!isNaN(b)&&b!=0)return b}a=a.parent()}}return 0}});c.extend(c.expr[":"],{data:function(a,b,d){return!!c.data(a,d[3])},focusable:function(a){var b=a.nodeName.toLowerCase(),d=c.attr(a,"tabindex");return(/input|select|textarea|button|object/.test(b)?
!a.disabled:"a"==b||"area"==b?a.href||!isNaN(d):!isNaN(d))&&!c(a)["area"==b?"parents":"closest"](":hidden").length},tabbable:function(a){var b=c.attr(a,"tabindex");return(isNaN(b)||b>=0)&&c(a).is(":focusable")}})}})(jQuery);
(function(c){var a=c.fn.remove;c.fn.remove=function(b,d){return this.each(function(){if(!d)if(!b||c.filter(b,[this]).length)c("*",this).add(this).each(function(){c(this).triggerHandler("remove")});return a.call(c(this),b,d)})};c.widget=function(b,d,g){var f=b.split(".")[0],h;b=b.split(".")[1];h=f+"-"+b;if(!g){g=d;d=c.Widget}c.expr[":"][h]=function(l){return!!c.data(l,b)};c[f]=c[f]||{};c[f][b]=function(l,n){arguments.length&&this._createWidget(l,n)};d=new d;d.options=c.extend({},d.options);c[f][b].prototype=
c.extend(true,d,{namespace:f,widgetName:b,widgetEventPrefix:c[f][b].prototype.widgetEventPrefix||b,widgetBaseClass:h},g);c.widget.bridge(b,c[f][b])};c.widget.bridge=function(b,d){c.fn[b]=function(g){var f=typeof g==="string",h=Array.prototype.slice.call(arguments,1),l=this;g=!f&&h.length?c.extend.apply(null,[true,g].concat(h)):g;if(f&&g.substring(0,1)==="_")return l;f?this.each(function(){var n=c.data(this,b),j=n&&c.isFunction(n[g])?n[g].apply(n,h):n;if(j!==n&&j!==undefined){l=j;return false}}):this.each(function(){var n=
c.data(this,b);if(n){g&&n.option(g);n._init()}else c.data(this,b,new d(g,this))});return l}};c.Widget=function(b,d){arguments.length&&this._createWidget(b,d)};c.Widget.prototype={widgetName:"widget",widgetEventPrefix:"",options:{disabled:false},_createWidget:function(b,d){this.element=c(d).data(this.widgetName,this);this.options=c.extend(true,{},this.options,c.metadata&&c.metadata.get(d)[this.widgetName],b);var g=this;this.element.bind("remove."+this.widgetName,function(){g.destroy()});this._create();
this._init()},_create:function(){},_init:function(){},destroy:function(){this.element.unbind("."+this.widgetName).removeData(this.widgetName);this.widget().unbind("."+this.widgetName).removeAttr("aria-disabled").removeClass(this.widgetBaseClass+"-disabled ui-state-disabled")},widget:function(){return this.element},option:function(b,d){var g=b,f=this;if(arguments.length===0)return c.extend({},f.options);if(typeof b==="string"){if(d===undefined)return this.options[b];g={};g[b]=d}c.each(g,function(h,
l){f._setOption(h,l)});return f},_setOption:function(b,d){this.options[b]=d;if(b==="disabled")this.widget()[d?"addClass":"removeClass"](this.widgetBaseClass+"-disabled ui-state-disabled").attr("aria-disabled",d);return this},enable:function(){return this._setOption("disabled",false)},disable:function(){return this._setOption("disabled",true)},_trigger:function(b,d,g){var f=this.options[b];d=c.Event(d);d.type=(b===this.widgetEventPrefix?b:this.widgetEventPrefix+b).toLowerCase();g=g||{};if(d.originalEvent){b=
c.event.props.length;for(var h;b;){h=c.event.props[--b];d[h]=d.originalEvent[h]}}this.element.trigger(d,g);return!(c.isFunction(f)&&f.call(this.element[0],d,g)===false||d.isDefaultPrevented())}}})(jQuery);
(function(c){c.widget("ui.mouse",{options:{cancel:":input,option",distance:1,delay:0},_mouseInit:function(){var a=this;this.element.bind("mousedown."+this.widgetName,function(b){return a._mouseDown(b)}).bind("click."+this.widgetName,function(b){if(a._preventClickEvent){a._preventClickEvent=false;b.stopImmediatePropagation();return false}});this.started=false},_mouseDestroy:function(){this.element.unbind("."+this.widgetName)},_mouseDown:function(a){a.originalEvent=a.originalEvent||{};if(!a.originalEvent.mouseHandled){this._mouseStarted&&
this._mouseUp(a);this._mouseDownEvent=a;var b=this,d=a.which==1,g=typeof this.options.cancel=="string"?c(a.target).parents().add(a.target).filter(this.options.cancel).length:false;if(!d||g||!this._mouseCapture(a))return true;this.mouseDelayMet=!this.options.delay;if(!this.mouseDelayMet)this._mouseDelayTimer=setTimeout(function(){b.mouseDelayMet=true},this.options.delay);if(this._mouseDistanceMet(a)&&this._mouseDelayMet(a)){this._mouseStarted=this._mouseStart(a)!==false;if(!this._mouseStarted){a.preventDefault();
return true}}this._mouseMoveDelegate=function(f){return b._mouseMove(f)};this._mouseUpDelegate=function(f){return b._mouseUp(f)};c(document).bind("mousemove."+this.widgetName,this._mouseMoveDelegate).bind("mouseup."+this.widgetName,this._mouseUpDelegate);c.browser.safari||a.preventDefault();return a.originalEvent.mouseHandled=true}},_mouseMove:function(a){if(c.browser.msie&&!a.button)return this._mouseUp(a);if(this._mouseStarted){this._mouseDrag(a);return a.preventDefault()}if(this._mouseDistanceMet(a)&&
this._mouseDelayMet(a))(this._mouseStarted=this._mouseStart(this._mouseDownEvent,a)!==false)?this._mouseDrag(a):this._mouseUp(a);return!this._mouseStarted},_mouseUp:function(a){c(document).unbind("mousemove."+this.widgetName,this._mouseMoveDelegate).unbind("mouseup."+this.widgetName,this._mouseUpDelegate);if(this._mouseStarted){this._mouseStarted=false;this._preventClickEvent=a.target==this._mouseDownEvent.target;this._mouseStop(a)}return false},_mouseDistanceMet:function(a){return Math.max(Math.abs(this._mouseDownEvent.pageX-
a.pageX),Math.abs(this._mouseDownEvent.pageY-a.pageY))>=this.options.distance},_mouseDelayMet:function(){return this.mouseDelayMet},_mouseStart:function(){},_mouseDrag:function(){},_mouseStop:function(){},_mouseCapture:function(){return true}})})(jQuery);
(function(c){c.ui=c.ui||{};var a=/left|center|right/,b=/top|center|bottom/,d=c.fn.position,g=c.fn.offset;c.fn.position=function(f){if(!f||!f.of)return d.apply(this,arguments);f=c.extend({},f);var h=c(f.of),l=(f.collision||"flip").split(" "),n=f.offset?f.offset.split(" "):[0,0],j,e,i;if(f.of.nodeType===9){j=h.width();e=h.height();i={top:0,left:0}}else if(f.of.scrollTo&&f.of.document){j=h.width();e=h.height();i={top:h.scrollTop(),left:h.scrollLeft()}}else if(f.of.preventDefault){f.at="left top";j=e=
0;i={top:f.of.pageY,left:f.of.pageX}}else{j=h.outerWidth();e=h.outerHeight();i=h.offset()}c.each(["my","at"],function(){var k=(f[this]||"").split(" ");if(k.length===1)k=a.test(k[0])?k.concat(["center"]):b.test(k[0])?["center"].concat(k):["center","center"];k[0]=a.test(k[0])?k[0]:"center";k[1]=b.test(k[1])?k[1]:"center";f[this]=k});if(l.length===1)l[1]=l[0];n[0]=parseInt(n[0],10)||0;if(n.length===1)n[1]=n[0];n[1]=parseInt(n[1],10)||0;if(f.at[0]==="right")i.left+=j;else if(f.at[0]==="center")i.left+=
j/2;if(f.at[1]==="bottom")i.top+=e;else if(f.at[1]==="center")i.top+=e/2;i.left+=n[0];i.top+=n[1];return this.each(function(){var k=c(this),m=k.outerWidth(),o=k.outerHeight(),p=c.extend({},i);if(f.my[0]==="right")p.left-=m;else if(f.my[0]==="center")p.left-=m/2;if(f.my[1]==="bottom")p.top-=o;else if(f.my[1]==="center")p.top-=o/2;p.left=parseInt(p.left);p.top=parseInt(p.top);c.each(["left","top"],function(q,r){c.ui.position[l[q]]&&c.ui.position[l[q]][r](p,{targetWidth:j,targetHeight:e,elemWidth:m,
elemHeight:o,offset:n,my:f.my,at:f.at})});c.fn.bgiframe&&k.bgiframe();k.offset(c.extend(p,{using:f.using}))})};c.ui.position={fit:{left:function(f,h){var l=c(window);l=f.left+h.elemWidth-l.width()-l.scrollLeft();f.left=l>0?f.left-l:Math.max(0,f.left)},top:function(f,h){var l=c(window);l=f.top+h.elemHeight-l.height()-l.scrollTop();f.top=l>0?f.top-l:Math.max(0,f.top)}},flip:{left:function(f,h){if(h.at[0]!=="center"){var l=c(window);l=f.left+h.elemWidth-l.width()-l.scrollLeft();var n=h.my[0]==="left"?
-h.elemWidth:h.my[0]==="right"?h.elemWidth:0,j=-2*h.offset[0];f.left+=f.left<0?n+h.targetWidth+j:l>0?n-h.targetWidth+j:0}},top:function(f,h){if(h.at[1]!=="center"){var l=c(window);l=f.top+h.elemHeight-l.height()-l.scrollTop();var n=h.my[1]==="top"?-h.elemHeight:h.my[1]==="bottom"?h.elemHeight:0,j=h.at[1]==="top"?h.targetHeight:-h.targetHeight,e=-2*h.offset[1];f.top+=f.top<0?n+h.targetHeight+e:l>0?n+j+e:0}}}};if(!c.offset.setOffset){c.offset.setOffset=function(f,h){if(/static/.test(c.curCSS(f,"position")))f.style.position=
"relative";var l=c(f),n=l.offset(),j=parseInt(c.curCSS(f,"top",true),10)||0,e=parseInt(c.curCSS(f,"left",true),10)||0;n={top:h.top-n.top+j,left:h.left-n.left+e};"using"in h?h.using.call(f,n):l.css(n)};c.fn.offset=function(f){var h=this[0];if(!h||!h.ownerDocument)return null;if(f)return this.each(function(){c.offset.setOffset(this,f)});return g.call(this)}}})(jQuery);
(function(c){c.widget("ui.draggable",c.ui.mouse,{widgetEventPrefix:"drag",options:{addClasses:true,appendTo:"parent",axis:false,connectToSortable:false,containment:false,cursor:"auto",cursorAt:false,grid:false,handle:false,helper:"original",iframeFix:false,opacity:false,refreshPositions:false,revert:false,revertDuration:500,scope:"default",scroll:true,scrollSensitivity:20,scrollSpeed:20,snap:false,snapMode:"both",snapTolerance:20,stack:false,zIndex:false},_create:function(){if(this.options.helper==
"original"&&!/^(?:r|a|f)/.test(this.element.css("position")))this.element[0].style.position="relative";this.options.addClasses&&this.element.addClass("ui-draggable");this.options.disabled&&this.element.addClass("ui-draggable-disabled");this._mouseInit()},destroy:function(){if(this.element.data("draggable")){this.element.removeData("draggable").unbind(".draggable").removeClass("ui-draggable ui-draggable-dragging ui-draggable-disabled");this._mouseDestroy();return this}},_mouseCapture:function(a){var b=
this.options;if(this.helper||b.disabled||c(a.target).is(".ui-resizable-handle"))return false;this.handle=this._getHandle(a);if(!this.handle)return false;return true},_mouseStart:function(a){var b=this.options;this.helper=this._createHelper(a);this._cacheHelperProportions();if(c.ui.ddmanager)c.ui.ddmanager.current=this;this._cacheMargins();this.cssPosition=this.helper.css("position");this.scrollParent=this.helper.scrollParent();this.offset=this.positionAbs=this.element.offset();this.offset={top:this.offset.top-
this.margins.top,left:this.offset.left-this.margins.left};c.extend(this.offset,{click:{left:a.pageX-this.offset.left,top:a.pageY-this.offset.top},parent:this._getParentOffset(),relative:this._getRelativeOffset()});this.originalPosition=this.position=this._generatePosition(a);this.originalPageX=a.pageX;this.originalPageY=a.pageY;b.cursorAt&&this._adjustOffsetFromHelper(b.cursorAt);b.containment&&this._setContainment();if(this._trigger("start",a)===false){this._clear();return false}this._cacheHelperProportions();
c.ui.ddmanager&&!b.dropBehaviour&&c.ui.ddmanager.prepareOffsets(this,a);this.helper.addClass("ui-draggable-dragging");this._mouseDrag(a,true);return true},_mouseDrag:function(a,b){this.position=this._generatePosition(a);this.positionAbs=this._convertPositionTo("absolute");if(!b){var d=this._uiHash();if(this._trigger("drag",a,d)===false){this._mouseUp({});return false}this.position=d.position}if(!this.options.axis||this.options.axis!="y")this.helper[0].style.left=this.position.left+"px";if(!this.options.axis||
this.options.axis!="x")this.helper[0].style.top=this.position.top+"px";c.ui.ddmanager&&c.ui.ddmanager.drag(this,a);return false},_mouseStop:function(a){var b=false;if(c.ui.ddmanager&&!this.options.dropBehaviour)b=c.ui.ddmanager.drop(this,a);if(this.dropped){b=this.dropped;this.dropped=false}if(!this.element[0]||!this.element[0].parentNode)return false;if(this.options.revert=="invalid"&&!b||this.options.revert=="valid"&&b||this.options.revert===true||c.isFunction(this.options.revert)&&this.options.revert.call(this.element,
b)){var d=this;c(this.helper).animate(this.originalPosition,parseInt(this.options.revertDuration,10),function(){d._trigger("stop",a)!==false&&d._clear()})}else this._trigger("stop",a)!==false&&this._clear();return false},cancel:function(){this.helper.is(".ui-draggable-dragging")?this._mouseUp({}):this._clear();return this},_getHandle:function(a){var b=!this.options.handle||!c(this.options.handle,this.element).length?true:false;c(this.options.handle,this.element).find("*").andSelf().each(function(){if(this==
a.target)b=true});return b},_createHelper:function(a){var b=this.options;a=c.isFunction(b.helper)?c(b.helper.apply(this.element[0],[a])):b.helper=="clone"?this.element.clone():this.element;a.parents("body").length||a.appendTo(b.appendTo=="parent"?this.element[0].parentNode:b.appendTo);a[0]!=this.element[0]&&!/(fixed|absolute)/.test(a.css("position"))&&a.css("position","absolute");return a},_adjustOffsetFromHelper:function(a){if(typeof a=="string")a=a.split(" ");if(c.isArray(a))a={left:+a[0],top:+a[1]||
0};if("left"in a)this.offset.click.left=a.left+this.margins.left;if("right"in a)this.offset.click.left=this.helperProportions.width-a.right+this.margins.left;if("top"in a)this.offset.click.top=a.top+this.margins.top;if("bottom"in a)this.offset.click.top=this.helperProportions.height-a.bottom+this.margins.top},_getParentOffset:function(){this.offsetParent=this.helper.offsetParent();var a=this.offsetParent.offset();if(this.cssPosition=="absolute"&&this.scrollParent[0]!=document&&c.ui.contains(this.scrollParent[0],
this.offsetParent[0])){a.left+=this.scrollParent.scrollLeft();a.top+=this.scrollParent.scrollTop()}if(this.offsetParent[0]==document.body||this.offsetParent[0].tagName&&this.offsetParent[0].tagName.toLowerCase()=="html"&&c.browser.msie)a={top:0,left:0};return{top:a.top+(parseInt(this.offsetParent.css("borderTopWidth"),10)||0),left:a.left+(parseInt(this.offsetParent.css("borderLeftWidth"),10)||0)}},_getRelativeOffset:function(){if(this.cssPosition=="relative"){var a=this.element.position();return{top:a.top-
(parseInt(this.helper.css("top"),10)||0)+this.scrollParent.scrollTop(),left:a.left-(parseInt(this.helper.css("left"),10)||0)+this.scrollParent.scrollLeft()}}else return{top:0,left:0}},_cacheMargins:function(){this.margins={left:parseInt(this.element.css("marginLeft"),10)||0,top:parseInt(this.element.css("marginTop"),10)||0}},_cacheHelperProportions:function(){this.helperProportions={width:this.helper.outerWidth(),height:this.helper.outerHeight()}},_setContainment:function(){var a=this.options;if(a.containment==
"parent")a.containment=this.helper[0].parentNode;if(a.containment=="document"||a.containment=="window")this.containment=[0-this.offset.relative.left-this.offset.parent.left,0-this.offset.relative.top-this.offset.parent.top,c(a.containment=="document"?document:window).width()-this.helperProportions.width-this.margins.left,(c(a.containment=="document"?document:window).height()||document.body.parentNode.scrollHeight)-this.helperProportions.height-this.margins.top];if(!/^(document|window|parent)$/.test(a.containment)&&
a.containment.constructor!=Array){var b=c(a.containment)[0];if(b){a=c(a.containment).offset();var d=c(b).css("overflow")!="hidden";this.containment=[a.left+(parseInt(c(b).css("borderLeftWidth"),10)||0)+(parseInt(c(b).css("paddingLeft"),10)||0)-this.margins.left,a.top+(parseInt(c(b).css("borderTopWidth"),10)||0)+(parseInt(c(b).css("paddingTop"),10)||0)-this.margins.top,a.left+(d?Math.max(b.scrollWidth,b.offsetWidth):b.offsetWidth)-(parseInt(c(b).css("borderLeftWidth"),10)||0)-(parseInt(c(b).css("paddingRight"),
10)||0)-this.helperProportions.width-this.margins.left,a.top+(d?Math.max(b.scrollHeight,b.offsetHeight):b.offsetHeight)-(parseInt(c(b).css("borderTopWidth"),10)||0)-(parseInt(c(b).css("paddingBottom"),10)||0)-this.helperProportions.height-this.margins.top]}}else if(a.containment.constructor==Array)this.containment=a.containment},_convertPositionTo:function(a,b){if(!b)b=this.position;var d=a=="absolute"?1:-1,g=this.cssPosition=="absolute"&&!(this.scrollParent[0]!=document&&c.ui.contains(this.scrollParent[0],
this.offsetParent[0]))?this.offsetParent:this.scrollParent,f=/(html|body)/i.test(g[0].tagName);return{top:b.top+this.offset.relative.top*d+this.offset.parent.top*d-(c.browser.safari&&c.browser.version<526&&this.cssPosition=="fixed"?0:(this.cssPosition=="fixed"?-this.scrollParent.scrollTop():f?0:g.scrollTop())*d),left:b.left+this.offset.relative.left*d+this.offset.parent.left*d-(c.browser.safari&&c.browser.version<526&&this.cssPosition=="fixed"?0:(this.cssPosition=="fixed"?-this.scrollParent.scrollLeft():
f?0:g.scrollLeft())*d)}},_generatePosition:function(a){var b=this.options,d=this.cssPosition=="absolute"&&!(this.scrollParent[0]!=document&&c.ui.contains(this.scrollParent[0],this.offsetParent[0]))?this.offsetParent:this.scrollParent,g=/(html|body)/i.test(d[0].tagName),f=a.pageX,h=a.pageY;if(this.originalPosition){if(this.containment){if(a.pageX-this.offset.click.left<this.containment[0])f=this.containment[0]+this.offset.click.left;if(a.pageY-this.offset.click.top<this.containment[1])h=this.containment[1]+
this.offset.click.top;if(a.pageX-this.offset.click.left>this.containment[2])f=this.containment[2]+this.offset.click.left;if(a.pageY-this.offset.click.top>this.containment[3])h=this.containment[3]+this.offset.click.top}if(b.grid){h=this.originalPageY+Math.round((h-this.originalPageY)/b.grid[1])*b.grid[1];h=this.containment?!(h-this.offset.click.top<this.containment[1]||h-this.offset.click.top>this.containment[3])?h:!(h-this.offset.click.top<this.containment[1])?h-b.grid[1]:h+b.grid[1]:h;f=this.originalPageX+
Math.round((f-this.originalPageX)/b.grid[0])*b.grid[0];f=this.containment?!(f-this.offset.click.left<this.containment[0]||f-this.offset.click.left>this.containment[2])?f:!(f-this.offset.click.left<this.containment[0])?f-b.grid[0]:f+b.grid[0]:f}}return{top:h-this.offset.click.top-this.offset.relative.top-this.offset.parent.top+(c.browser.safari&&c.browser.version<526&&this.cssPosition=="fixed"?0:this.cssPosition=="fixed"?-this.scrollParent.scrollTop():g?0:d.scrollTop()),left:f-this.offset.click.left-
this.offset.relative.left-this.offset.parent.left+(c.browser.safari&&c.browser.version<526&&this.cssPosition=="fixed"?0:this.cssPosition=="fixed"?-this.scrollParent.scrollLeft():g?0:d.scrollLeft())}},_clear:function(){this.helper.removeClass("ui-draggable-dragging");this.helper[0]!=this.element[0]&&!this.cancelHelperRemoval&&this.helper.remove();this.helper=null;this.cancelHelperRemoval=false},_trigger:function(a,b,d){d=d||this._uiHash();c.ui.plugin.call(this,a,[b,d]);if(a=="drag")this.positionAbs=
this._convertPositionTo("absolute");return c.Widget.prototype._trigger.call(this,a,b,d)},plugins:{},_uiHash:function(){return{helper:this.helper,position:this.position,originalPosition:this.originalPosition,offset:this.positionAbs}}});c.extend(c.ui.draggable,{version:"1.8.2"});c.ui.plugin.add("draggable","connectToSortable",{start:function(a,b){var d=c(this).data("draggable"),g=d.options,f=c.extend({},b,{item:d.element});d.sortables=[];c(g.connectToSortable).each(function(){var h=c.data(this,"sortable");
if(h&&!h.options.disabled){d.sortables.push({instance:h,shouldRevert:h.options.revert});h._refreshItems();h._trigger("activate",a,f)}})},stop:function(a,b){var d=c(this).data("draggable"),g=c.extend({},b,{item:d.element});c.each(d.sortables,function(){if(this.instance.isOver){this.instance.isOver=0;d.cancelHelperRemoval=true;this.instance.cancelHelperRemoval=false;if(this.shouldRevert)this.instance.options.revert=true;this.instance._mouseStop(a);this.instance.options.helper=this.instance.options._helper;
d.options.helper=="original"&&this.instance.currentItem.css({top:"auto",left:"auto"})}else{this.instance.cancelHelperRemoval=false;this.instance._trigger("deactivate",a,g)}})},drag:function(a,b){var d=c(this).data("draggable"),g=this;c.each(d.sortables,function(){this.instance.positionAbs=d.positionAbs;this.instance.helperProportions=d.helperProportions;this.instance.offset.click=d.offset.click;if(this.instance._intersectsWith(this.instance.containerCache)){if(!this.instance.isOver){this.instance.isOver=
1;this.instance.currentItem=c(g).clone().appendTo(this.instance.element).data("sortable-item",true);this.instance.options._helper=this.instance.options.helper;this.instance.options.helper=function(){return b.helper[0]};a.target=this.instance.currentItem[0];this.instance._mouseCapture(a,true);this.instance._mouseStart(a,true,true);this.instance.offset.click.top=d.offset.click.top;this.instance.offset.click.left=d.offset.click.left;this.instance.offset.parent.left-=d.offset.parent.left-this.instance.offset.parent.left;
this.instance.offset.parent.top-=d.offset.parent.top-this.instance.offset.parent.top;d._trigger("toSortable",a);d.dropped=this.instance.element;d.currentItem=d.element;this.instance.fromOutside=d}this.instance.currentItem&&this.instance._mouseDrag(a)}else if(this.instance.isOver){this.instance.isOver=0;this.instance.cancelHelperRemoval=true;this.instance.options.revert=false;this.instance._trigger("out",a,this.instance._uiHash(this.instance));this.instance._mouseStop(a,true);this.instance.options.helper=
this.instance.options._helper;this.instance.currentItem.remove();this.instance.placeholder&&this.instance.placeholder.remove();d._trigger("fromSortable",a);d.dropped=false}})}});c.ui.plugin.add("draggable","cursor",{start:function(){var a=c("body"),b=c(this).data("draggable").options;if(a.css("cursor"))b._cursor=a.css("cursor");a.css("cursor",b.cursor)},stop:function(){var a=c(this).data("draggable").options;a._cursor&&c("body").css("cursor",a._cursor)}});c.ui.plugin.add("draggable","iframeFix",{start:function(){var a=
c(this).data("draggable").options;c(a.iframeFix===true?"iframe":a.iframeFix).each(function(){c('<div class="ui-draggable-iframeFix" style="background: #fff;"></div>').css({width:this.offsetWidth+"px",height:this.offsetHeight+"px",position:"absolute",opacity:"0.001",zIndex:1E3}).css(c(this).offset()).appendTo("body")})},stop:function(){c("div.ui-draggable-iframeFix").each(function(){this.parentNode.removeChild(this)})}});c.ui.plugin.add("draggable","opacity",{start:function(a,b){var d=c(b.helper),
g=c(this).data("draggable").options;if(d.css("opacity"))g._opacity=d.css("opacity");d.css("opacity",g.opacity)},stop:function(a,b){var d=c(this).data("draggable").options;d._opacity&&c(b.helper).css("opacity",d._opacity)}});c.ui.plugin.add("draggable","scroll",{start:function(){var a=c(this).data("draggable");if(a.scrollParent[0]!=document&&a.scrollParent[0].tagName!="HTML")a.overflowOffset=a.scrollParent.offset()},drag:function(a){var b=c(this).data("draggable"),d=b.options,g=false;if(b.scrollParent[0]!=
document&&b.scrollParent[0].tagName!="HTML"){if(!d.axis||d.axis!="x")if(b.overflowOffset.top+b.scrollParent[0].offsetHeight-a.pageY<d.scrollSensitivity)b.scrollParent[0].scrollTop=g=b.scrollParent[0].scrollTop+d.scrollSpeed;else if(a.pageY-b.overflowOffset.top<d.scrollSensitivity)b.scrollParent[0].scrollTop=g=b.scrollParent[0].scrollTop-d.scrollSpeed;if(!d.axis||d.axis!="y")if(b.overflowOffset.left+b.scrollParent[0].offsetWidth-a.pageX<d.scrollSensitivity)b.scrollParent[0].scrollLeft=g=b.scrollParent[0].scrollLeft+
d.scrollSpeed;else if(a.pageX-b.overflowOffset.left<d.scrollSensitivity)b.scrollParent[0].scrollLeft=g=b.scrollParent[0].scrollLeft-d.scrollSpeed}else{if(!d.axis||d.axis!="x")if(a.pageY-c(document).scrollTop()<d.scrollSensitivity)g=c(document).scrollTop(c(document).scrollTop()-d.scrollSpeed);else if(c(window).height()-(a.pageY-c(document).scrollTop())<d.scrollSensitivity)g=c(document).scrollTop(c(document).scrollTop()+d.scrollSpeed);if(!d.axis||d.axis!="y")if(a.pageX-c(document).scrollLeft()<d.scrollSensitivity)g=
c(document).scrollLeft(c(document).scrollLeft()-d.scrollSpeed);else if(c(window).width()-(a.pageX-c(document).scrollLeft())<d.scrollSensitivity)g=c(document).scrollLeft(c(document).scrollLeft()+d.scrollSpeed)}g!==false&&c.ui.ddmanager&&!d.dropBehaviour&&c.ui.ddmanager.prepareOffsets(b,a)}});c.ui.plugin.add("draggable","snap",{start:function(){var a=c(this).data("draggable"),b=a.options;a.snapElements=[];c(b.snap.constructor!=String?b.snap.items||":data(draggable)":b.snap).each(function(){var d=c(this),
g=d.offset();this!=a.element[0]&&a.snapElements.push({item:this,width:d.outerWidth(),height:d.outerHeight(),top:g.top,left:g.left})})},drag:function(a,b){for(var d=c(this).data("draggable"),g=d.options,f=g.snapTolerance,h=b.offset.left,l=h+d.helperProportions.width,n=b.offset.top,j=n+d.helperProportions.height,e=d.snapElements.length-1;e>=0;e--){var i=d.snapElements[e].left,k=i+d.snapElements[e].width,m=d.snapElements[e].top,o=m+d.snapElements[e].height;if(i-f<h&&h<k+f&&m-f<n&&n<o+f||i-f<h&&h<k+f&&
m-f<j&&j<o+f||i-f<l&&l<k+f&&m-f<n&&n<o+f||i-f<l&&l<k+f&&m-f<j&&j<o+f){if(g.snapMode!="inner"){var p=Math.abs(m-j)<=f,q=Math.abs(o-n)<=f,r=Math.abs(i-l)<=f,t=Math.abs(k-h)<=f;if(p)b.position.top=d._convertPositionTo("relative",{top:m-d.helperProportions.height,left:0}).top-d.margins.top;if(q)b.position.top=d._convertPositionTo("relative",{top:o,left:0}).top-d.margins.top;if(r)b.position.left=d._convertPositionTo("relative",{top:0,left:i-d.helperProportions.width}).left-d.margins.left;if(t)b.position.left=
d._convertPositionTo("relative",{top:0,left:k}).left-d.margins.left}var s=p||q||r||t;if(g.snapMode!="outer"){p=Math.abs(m-n)<=f;q=Math.abs(o-j)<=f;r=Math.abs(i-h)<=f;t=Math.abs(k-l)<=f;if(p)b.position.top=d._convertPositionTo("relative",{top:m,left:0}).top-d.margins.top;if(q)b.position.top=d._convertPositionTo("relative",{top:o-d.helperProportions.height,left:0}).top-d.margins.top;if(r)b.position.left=d._convertPositionTo("relative",{top:0,left:i}).left-d.margins.left;if(t)b.position.left=d._convertPositionTo("relative",
{top:0,left:k-d.helperProportions.width}).left-d.margins.left}if(!d.snapElements[e].snapping&&(p||q||r||t||s))d.options.snap.snap&&d.options.snap.snap.call(d.element,a,c.extend(d._uiHash(),{snapItem:d.snapElements[e].item}));d.snapElements[e].snapping=p||q||r||t||s}else{d.snapElements[e].snapping&&d.options.snap.release&&d.options.snap.release.call(d.element,a,c.extend(d._uiHash(),{snapItem:d.snapElements[e].item}));d.snapElements[e].snapping=false}}}});c.ui.plugin.add("draggable","stack",{start:function(){var a=
c(this).data("draggable").options;a=c.makeArray(c(a.stack)).sort(function(d,g){return(parseInt(c(d).css("zIndex"),10)||0)-(parseInt(c(g).css("zIndex"),10)||0)});if(a.length){var b=parseInt(a[0].style.zIndex)||0;c(a).each(function(d){this.style.zIndex=b+d});this[0].style.zIndex=b+a.length}}});c.ui.plugin.add("draggable","zIndex",{start:function(a,b){var d=c(b.helper),g=c(this).data("draggable").options;if(d.css("zIndex"))g._zIndex=d.css("zIndex");d.css("zIndex",g.zIndex)},stop:function(a,b){var d=
c(this).data("draggable").options;d._zIndex&&c(b.helper).css("zIndex",d._zIndex)}})})(jQuery);
(function(c){c.widget("ui.droppable",{widgetEventPrefix:"drop",options:{accept:"*",activeClass:false,addClasses:true,greedy:false,hoverClass:false,scope:"default",tolerance:"intersect"},_create:function(){var a=this.options,b=a.accept;this.isover=0;this.isout=1;this.accept=c.isFunction(b)?b:function(d){return d.is(b)};this.proportions={width:this.element[0].offsetWidth,height:this.element[0].offsetHeight};c.ui.ddmanager.droppables[a.scope]=c.ui.ddmanager.droppables[a.scope]||[];c.ui.ddmanager.droppables[a.scope].push(this);
a.addClasses&&this.element.addClass("ui-droppable")},destroy:function(){for(var a=c.ui.ddmanager.droppables[this.options.scope],b=0;b<a.length;b++)a[b]==this&&a.splice(b,1);this.element.removeClass("ui-droppable ui-droppable-disabled").removeData("droppable").unbind(".droppable");return this},_setOption:function(a,b){if(a=="accept")this.accept=c.isFunction(b)?b:function(d){return d.is(b)};c.Widget.prototype._setOption.apply(this,arguments)},_activate:function(a){var b=c.ui.ddmanager.current;this.options.activeClass&&
this.element.addClass(this.options.activeClass);b&&this._trigger("activate",a,this.ui(b))},_deactivate:function(a){var b=c.ui.ddmanager.current;this.options.activeClass&&this.element.removeClass(this.options.activeClass);b&&this._trigger("deactivate",a,this.ui(b))},_over:function(a){var b=c.ui.ddmanager.current;if(!(!b||(b.currentItem||b.element)[0]==this.element[0]))if(this.accept.call(this.element[0],b.currentItem||b.element)){this.options.hoverClass&&this.element.addClass(this.options.hoverClass);
this._trigger("over",a,this.ui(b))}},_out:function(a){var b=c.ui.ddmanager.current;if(!(!b||(b.currentItem||b.element)[0]==this.element[0]))if(this.accept.call(this.element[0],b.currentItem||b.element)){this.options.hoverClass&&this.element.removeClass(this.options.hoverClass);this._trigger("out",a,this.ui(b))}},_drop:function(a,b){var d=b||c.ui.ddmanager.current;if(!d||(d.currentItem||d.element)[0]==this.element[0])return false;var g=false;this.element.find(":data(droppable)").not(".ui-draggable-dragging").each(function(){var f=
c.data(this,"droppable");if(f.options.greedy&&!f.options.disabled&&f.options.scope==d.options.scope&&f.accept.call(f.element[0],d.currentItem||d.element)&&c.ui.intersect(d,c.extend(f,{offset:f.element.offset()}),f.options.tolerance)){g=true;return false}});if(g)return false;if(this.accept.call(this.element[0],d.currentItem||d.element)){this.options.activeClass&&this.element.removeClass(this.options.activeClass);this.options.hoverClass&&this.element.removeClass(this.options.hoverClass);this._trigger("drop",
a,this.ui(d));return this.element}return false},ui:function(a){return{draggable:a.currentItem||a.element,helper:a.helper,position:a.position,offset:a.positionAbs}}});c.extend(c.ui.droppable,{version:"1.8.2"});c.ui.intersect=function(a,b,d){if(!b.offset)return false;var g=(a.positionAbs||a.position.absolute).left,f=g+a.helperProportions.width,h=(a.positionAbs||a.position.absolute).top,l=h+a.helperProportions.height,n=b.offset.left,j=n+b.proportions.width,e=b.offset.top,i=e+b.proportions.height;switch(d){case "fit":return n<
g&&f<j&&e<h&&l<i;case "intersect":return n<g+a.helperProportions.width/2&&f-a.helperProportions.width/2<j&&e<h+a.helperProportions.height/2&&l-a.helperProportions.height/2<i;case "pointer":return c.ui.isOver((a.positionAbs||a.position.absolute).top+(a.clickOffset||a.offset.click).top,(a.positionAbs||a.position.absolute).left+(a.clickOffset||a.offset.click).left,e,n,b.proportions.height,b.proportions.width);case "touch":return(h>=e&&h<=i||l>=e&&l<=i||h<e&&l>i)&&(g>=n&&g<=j||f>=n&&f<=j||g<n&&f>j);default:return false}};
c.ui.ddmanager={current:null,droppables:{"default":[]},prepareOffsets:function(a,b){var d=c.ui.ddmanager.droppables[a.options.scope]||[],g=b?b.type:null,f=(a.currentItem||a.element).find(":data(droppable)").andSelf(),h=0;a:for(;h<d.length;h++)if(!(d[h].options.disabled||a&&!d[h].accept.call(d[h].element[0],a.currentItem||a.element))){for(var l=0;l<f.length;l++)if(f[l]==d[h].element[0]){d[h].proportions.height=0;continue a}d[h].visible=d[h].element.css("display")!="none";if(d[h].visible){d[h].offset=
d[h].element.offset();d[h].proportions={width:d[h].element[0].offsetWidth,height:d[h].element[0].offsetHeight};g=="mousedown"&&d[h]._activate.call(d[h],b)}}},drop:function(a,b){var d=false;c.each(c.ui.ddmanager.droppables[a.options.scope]||[],function(){if(this.options){if(!this.options.disabled&&this.visible&&c.ui.intersect(a,this,this.options.tolerance))d=d||this._drop.call(this,b);if(!this.options.disabled&&this.visible&&this.accept.call(this.element[0],a.currentItem||a.element)){this.isout=1;
this.isover=0;this._deactivate.call(this,b)}}});return d},drag:function(a,b){a.options.refreshPositions&&c.ui.ddmanager.prepareOffsets(a,b);c.each(c.ui.ddmanager.droppables[a.options.scope]||[],function(){if(!(this.options.disabled||this.greedyChild||!this.visible)){var d=c.ui.intersect(a,this,this.options.tolerance);if(d=!d&&this.isover==1?"isout":d&&this.isover==0?"isover":null){var g;if(this.options.greedy){var f=this.element.parents(":data(droppable):eq(0)");if(f.length){g=c.data(f[0],"droppable");
g.greedyChild=d=="isover"?1:0}}if(g&&d=="isover"){g.isover=0;g.isout=1;g._out.call(g,b)}this[d]=1;this[d=="isout"?"isover":"isout"]=0;this[d=="isover"?"_over":"_out"].call(this,b);if(g&&d=="isout"){g.isout=0;g.isover=1;g._over.call(g,b)}}}})}}})(jQuery);
(function(c){c.widget("ui.sortable",c.ui.mouse,{widgetEventPrefix:"sort",options:{appendTo:"parent",axis:false,connectWith:false,containment:false,cursor:"auto",cursorAt:false,dropOnEmpty:true,forcePlaceholderSize:false,forceHelperSize:false,grid:false,handle:false,helper:"original",items:"> *",opacity:false,placeholder:false,revert:false,scroll:true,scrollSensitivity:20,scrollSpeed:20,scope:"default",tolerance:"intersect",zIndex:1E3},_create:function(){this.containerCache={};this.element.addClass("ui-sortable");
this.refresh();this.floating=this.items.length?/left|right/.test(this.items[0].item.css("float")):false;this.offset=this.element.offset();this._mouseInit()},destroy:function(){this.element.removeClass("ui-sortable ui-sortable-disabled").removeData("sortable").unbind(".sortable");this._mouseDestroy();for(var a=this.items.length-1;a>=0;a--)this.items[a].item.removeData("sortable-item");return this},_setOption:function(a,b){if(a==="disabled"){this.options[a]=b;this.widget()[b?"addClass":"removeClass"]("ui-sortable-disabled")}else c.Widget.prototype._setOption.apply(this,
arguments)},_mouseCapture:function(a,b){if(this.reverting)return false;if(this.options.disabled||this.options.type=="static")return false;this._refreshItems(a);var d=null,g=this;c(a.target).parents().each(function(){if(c.data(this,"sortable-item")==g){d=c(this);return false}});if(c.data(a.target,"sortable-item")==g)d=c(a.target);if(!d)return false;if(this.options.handle&&!b){var f=false;c(this.options.handle,d).find("*").andSelf().each(function(){if(this==a.target)f=true});if(!f)return false}this.currentItem=
d;this._removeCurrentsFromItems();return true},_mouseStart:function(a,b,d){b=this.options;this.currentContainer=this;this.refreshPositions();this.helper=this._createHelper(a);this._cacheHelperProportions();this._cacheMargins();this.scrollParent=this.helper.scrollParent();this.offset=this.currentItem.offset();this.offset={top:this.offset.top-this.margins.top,left:this.offset.left-this.margins.left};this.helper.css("position","absolute");this.cssPosition=this.helper.css("position");c.extend(this.offset,
{click:{left:a.pageX-this.offset.left,top:a.pageY-this.offset.top},parent:this._getParentOffset(),relative:this._getRelativeOffset()});this.originalPosition=this._generatePosition(a);this.originalPageX=a.pageX;this.originalPageY=a.pageY;b.cursorAt&&this._adjustOffsetFromHelper(b.cursorAt);this.domPosition={prev:this.currentItem.prev()[0],parent:this.currentItem.parent()[0]};this.helper[0]!=this.currentItem[0]&&this.currentItem.hide();this._createPlaceholder();b.containment&&this._setContainment();
if(b.cursor){if(c("body").css("cursor"))this._storedCursor=c("body").css("cursor");c("body").css("cursor",b.cursor)}if(b.opacity){if(this.helper.css("opacity"))this._storedOpacity=this.helper.css("opacity");this.helper.css("opacity",b.opacity)}if(b.zIndex){if(this.helper.css("zIndex"))this._storedZIndex=this.helper.css("zIndex");this.helper.css("zIndex",b.zIndex)}if(this.scrollParent[0]!=document&&this.scrollParent[0].tagName!="HTML")this.overflowOffset=this.scrollParent.offset();this._trigger("start",
a,this._uiHash());this._preserveHelperProportions||this._cacheHelperProportions();if(!d)for(d=this.containers.length-1;d>=0;d--)this.containers[d]._trigger("activate",a,this._uiHash(this));if(c.ui.ddmanager)c.ui.ddmanager.current=this;c.ui.ddmanager&&!b.dropBehaviour&&c.ui.ddmanager.prepareOffsets(this,a);this.dragging=true;this.helper.addClass("ui-sortable-helper");this._mouseDrag(a);return true},_mouseDrag:function(a){this.position=this._generatePosition(a);this.positionAbs=this._convertPositionTo("absolute");
if(!this.lastPositionAbs)this.lastPositionAbs=this.positionAbs;if(this.options.scroll){var b=this.options,d=false;if(this.scrollParent[0]!=document&&this.scrollParent[0].tagName!="HTML"){if(this.overflowOffset.top+this.scrollParent[0].offsetHeight-a.pageY<b.scrollSensitivity)this.scrollParent[0].scrollTop=d=this.scrollParent[0].scrollTop+b.scrollSpeed;else if(a.pageY-this.overflowOffset.top<b.scrollSensitivity)this.scrollParent[0].scrollTop=d=this.scrollParent[0].scrollTop-b.scrollSpeed;if(this.overflowOffset.left+
this.scrollParent[0].offsetWidth-a.pageX<b.scrollSensitivity)this.scrollParent[0].scrollLeft=d=this.scrollParent[0].scrollLeft+b.scrollSpeed;else if(a.pageX-this.overflowOffset.left<b.scrollSensitivity)this.scrollParent[0].scrollLeft=d=this.scrollParent[0].scrollLeft-b.scrollSpeed}else{if(a.pageY-c(document).scrollTop()<b.scrollSensitivity)d=c(document).scrollTop(c(document).scrollTop()-b.scrollSpeed);else if(c(window).height()-(a.pageY-c(document).scrollTop())<b.scrollSensitivity)d=c(document).scrollTop(c(document).scrollTop()+
b.scrollSpeed);if(a.pageX-c(document).scrollLeft()<b.scrollSensitivity)d=c(document).scrollLeft(c(document).scrollLeft()-b.scrollSpeed);else if(c(window).width()-(a.pageX-c(document).scrollLeft())<b.scrollSensitivity)d=c(document).scrollLeft(c(document).scrollLeft()+b.scrollSpeed)}d!==false&&c.ui.ddmanager&&!b.dropBehaviour&&c.ui.ddmanager.prepareOffsets(this,a)}this.positionAbs=this._convertPositionTo("absolute");if(!this.options.axis||this.options.axis!="y")this.helper[0].style.left=this.position.left+
"px";if(!this.options.axis||this.options.axis!="x")this.helper[0].style.top=this.position.top+"px";for(b=this.items.length-1;b>=0;b--){d=this.items[b];var g=d.item[0],f=this._intersectsWithPointer(d);if(f)if(g!=this.currentItem[0]&&this.placeholder[f==1?"next":"prev"]()[0]!=g&&!c.ui.contains(this.placeholder[0],g)&&(this.options.type=="semi-dynamic"?!c.ui.contains(this.element[0],g):true)){this.direction=f==1?"down":"up";if(this.options.tolerance=="pointer"||this._intersectsWithSides(d))this._rearrange(a,
d);else break;this._trigger("change",a,this._uiHash());break}}this._contactContainers(a);c.ui.ddmanager&&c.ui.ddmanager.drag(this,a);this._trigger("sort",a,this._uiHash());this.lastPositionAbs=this.positionAbs;return false},_mouseStop:function(a,b){if(a){c.ui.ddmanager&&!this.options.dropBehaviour&&c.ui.ddmanager.drop(this,a);if(this.options.revert){var d=this,g=d.placeholder.offset();d.reverting=true;c(this.helper).animate({left:g.left-this.offset.parent.left-d.margins.left+(this.offsetParent[0]==
document.body?0:this.offsetParent[0].scrollLeft),top:g.top-this.offset.parent.top-d.margins.top+(this.offsetParent[0]==document.body?0:this.offsetParent[0].scrollTop)},parseInt(this.options.revert,10)||500,function(){d._clear(a)})}else this._clear(a,b);return false}},cancel:function(){if(this.dragging){this._mouseUp();this.options.helper=="original"?this.currentItem.css(this._storedCSS).removeClass("ui-sortable-helper"):this.currentItem.show();for(var a=this.containers.length-1;a>=0;a--){this.containers[a]._trigger("deactivate",
null,this._uiHash(this));if(this.containers[a].containerCache.over){this.containers[a]._trigger("out",null,this._uiHash(this));this.containers[a].containerCache.over=0}}}this.placeholder[0].parentNode&&this.placeholder[0].parentNode.removeChild(this.placeholder[0]);this.options.helper!="original"&&this.helper&&this.helper[0].parentNode&&this.helper.remove();c.extend(this,{helper:null,dragging:false,reverting:false,_noFinalSort:null});this.domPosition.prev?c(this.domPosition.prev).after(this.currentItem):
c(this.domPosition.parent).prepend(this.currentItem);return this},serialize:function(a){var b=this._getItemsAsjQuery(a&&a.connected),d=[];a=a||{};c(b).each(function(){var g=(c(a.item||this).attr(a.attribute||"id")||"").match(a.expression||/(.+)[-=_](.+)/);if(g)d.push((a.key||g[1]+"[]")+"="+(a.key&&a.expression?g[1]:g[2]))});return d.join("&")},toArray:function(a){var b=this._getItemsAsjQuery(a&&a.connected),d=[];a=a||{};b.each(function(){d.push(c(a.item||this).attr(a.attribute||"id")||"")});return d},
_intersectsWith:function(a){var b=this.positionAbs.left,d=b+this.helperProportions.width,g=this.positionAbs.top,f=g+this.helperProportions.height,h=a.left,l=h+a.width,n=a.top,j=n+a.height,e=this.offset.click.top,i=this.offset.click.left;e=g+e>n&&g+e<j&&b+i>h&&b+i<l;return this.options.tolerance=="pointer"||this.options.forcePointerForContainers||this.options.tolerance!="pointer"&&this.helperProportions[this.floating?"width":"height"]>a[this.floating?"width":"height"]?e:h<b+this.helperProportions.width/
2&&d-this.helperProportions.width/2<l&&n<g+this.helperProportions.height/2&&f-this.helperProportions.height/2<j},_intersectsWithPointer:function(a){var b=c.ui.isOverAxis(this.positionAbs.top+this.offset.click.top,a.top,a.height);a=c.ui.isOverAxis(this.positionAbs.left+this.offset.click.left,a.left,a.width);b=b&&a;a=this._getDragVerticalDirection();var d=this._getDragHorizontalDirection();if(!b)return false;return this.floating?d&&d=="right"||a=="down"?2:1:a&&(a=="down"?2:1)},_intersectsWithSides:function(a){var b=
c.ui.isOverAxis(this.positionAbs.top+this.offset.click.top,a.top+a.height/2,a.height);a=c.ui.isOverAxis(this.positionAbs.left+this.offset.click.left,a.left+a.width/2,a.width);var d=this._getDragVerticalDirection(),g=this._getDragHorizontalDirection();return this.floating&&g?g=="right"&&a||g=="left"&&!a:d&&(d=="down"&&b||d=="up"&&!b)},_getDragVerticalDirection:function(){var a=this.positionAbs.top-this.lastPositionAbs.top;return a!=0&&(a>0?"down":"up")},_getDragHorizontalDirection:function(){var a=
this.positionAbs.left-this.lastPositionAbs.left;return a!=0&&(a>0?"right":"left")},refresh:function(a){this._refreshItems(a);this.refreshPositions();return this},_connectWith:function(){var a=this.options;return a.connectWith.constructor==String?[a.connectWith]:a.connectWith},_getItemsAsjQuery:function(a){var b=[],d=[],g=this._connectWith();if(g&&a)for(a=g.length-1;a>=0;a--)for(var f=c(g[a]),h=f.length-1;h>=0;h--){var l=c.data(f[h],"sortable");if(l&&l!=this&&!l.options.disabled)d.push([c.isFunction(l.options.items)?
l.options.items.call(l.element):c(l.options.items,l.element).not(".ui-sortable-helper").not(".ui-sortable-placeholder"),l])}d.push([c.isFunction(this.options.items)?this.options.items.call(this.element,null,{options:this.options,item:this.currentItem}):c(this.options.items,this.element).not(".ui-sortable-helper").not(".ui-sortable-placeholder"),this]);for(a=d.length-1;a>=0;a--)d[a][0].each(function(){b.push(this)});return c(b)},_removeCurrentsFromItems:function(){for(var a=this.currentItem.find(":data(sortable-item)"),
b=0;b<this.items.length;b++)for(var d=0;d<a.length;d++)a[d]==this.items[b].item[0]&&this.items.splice(b,1)},_refreshItems:function(a){this.items=[];this.containers=[this];var b=this.items,d=[[c.isFunction(this.options.items)?this.options.items.call(this.element[0],a,{item:this.currentItem}):c(this.options.items,this.element),this]],g=this._connectWith();if(g)for(var f=g.length-1;f>=0;f--)for(var h=c(g[f]),l=h.length-1;l>=0;l--){var n=c.data(h[l],"sortable");if(n&&n!=this&&!n.options.disabled){d.push([c.isFunction(n.options.items)?
n.options.items.call(n.element[0],a,{item:this.currentItem}):c(n.options.items,n.element),n]);this.containers.push(n)}}for(f=d.length-1;f>=0;f--){a=d[f][1];g=d[f][0];l=0;for(h=g.length;l<h;l++){n=c(g[l]);n.data("sortable-item",a);b.push({item:n,instance:a,width:0,height:0,left:0,top:0})}}},refreshPositions:function(a){if(this.offsetParent&&this.helper)this.offset.parent=this._getParentOffset();for(var b=this.items.length-1;b>=0;b--){var d=this.items[b],g=this.options.toleranceElement?c(this.options.toleranceElement,
d.item):d.item;if(!a){d.width=g.outerWidth();d.height=g.outerHeight()}g=g.offset();d.left=g.left;d.top=g.top}if(this.options.custom&&this.options.custom.refreshContainers)this.options.custom.refreshContainers.call(this);else for(b=this.containers.length-1;b>=0;b--){g=this.containers[b].element.offset();this.containers[b].containerCache.left=g.left;this.containers[b].containerCache.top=g.top;this.containers[b].containerCache.width=this.containers[b].element.outerWidth();this.containers[b].containerCache.height=
this.containers[b].element.outerHeight()}return this},_createPlaceholder:function(a){var b=a||this,d=b.options;if(!d.placeholder||d.placeholder.constructor==String){var g=d.placeholder;d.placeholder={element:function(){var f=c(document.createElement(b.currentItem[0].nodeName)).addClass(g||b.currentItem[0].className+" ui-sortable-placeholder").removeClass("ui-sortable-helper")[0];if(!g)f.style.visibility="hidden";return f},update:function(f,h){if(!(g&&!d.forcePlaceholderSize)){h.height()||h.height(b.currentItem.innerHeight()-
parseInt(b.currentItem.css("paddingTop")||0,10)-parseInt(b.currentItem.css("paddingBottom")||0,10));h.width()||h.width(b.currentItem.innerWidth()-parseInt(b.currentItem.css("paddingLeft")||0,10)-parseInt(b.currentItem.css("paddingRight")||0,10))}}}}b.placeholder=c(d.placeholder.element.call(b.element,b.currentItem));b.currentItem.after(b.placeholder);d.placeholder.update(b,b.placeholder)},_contactContainers:function(a){for(var b=null,d=null,g=this.containers.length-1;g>=0;g--)if(!c.ui.contains(this.currentItem[0],
this.containers[g].element[0]))if(this._intersectsWith(this.containers[g].containerCache)){if(!(b&&c.ui.contains(this.containers[g].element[0],b.element[0]))){b=this.containers[g];d=g}}else if(this.containers[g].containerCache.over){this.containers[g]._trigger("out",a,this._uiHash(this));this.containers[g].containerCache.over=0}if(b)if(this.containers.length===1){this.containers[d]._trigger("over",a,this._uiHash(this));this.containers[d].containerCache.over=1}else if(this.currentContainer!=this.containers[d]){b=
1E4;g=null;for(var f=this.positionAbs[this.containers[d].floating?"left":"top"],h=this.items.length-1;h>=0;h--)if(c.ui.contains(this.containers[d].element[0],this.items[h].item[0])){var l=this.items[h][this.containers[d].floating?"left":"top"];if(Math.abs(l-f)<b){b=Math.abs(l-f);g=this.items[h]}}if(g||this.options.dropOnEmpty){this.currentContainer=this.containers[d];g?this._rearrange(a,g,null,true):this._rearrange(a,null,this.containers[d].element,true);this._trigger("change",a,this._uiHash());this.containers[d]._trigger("change",
a,this._uiHash(this));this.options.placeholder.update(this.currentContainer,this.placeholder);this.containers[d]._trigger("over",a,this._uiHash(this));this.containers[d].containerCache.over=1}}},_createHelper:function(a){var b=this.options;a=c.isFunction(b.helper)?c(b.helper.apply(this.element[0],[a,this.currentItem])):b.helper=="clone"?this.currentItem.clone():this.currentItem;a.parents("body").length||c(b.appendTo!="parent"?b.appendTo:this.currentItem[0].parentNode)[0].appendChild(a[0]);if(a[0]==
this.currentItem[0])this._storedCSS={width:this.currentItem[0].style.width,height:this.currentItem[0].style.height,position:this.currentItem.css("position"),top:this.currentItem.css("top"),left:this.currentItem.css("left")};if(a[0].style.width==""||b.forceHelperSize)a.width(this.currentItem.width());if(a[0].style.height==""||b.forceHelperSize)a.height(this.currentItem.height());return a},_adjustOffsetFromHelper:function(a){if(typeof a=="string")a=a.split(" ");if(c.isArray(a))a={left:+a[0],top:+a[1]||
0};if("left"in a)this.offset.click.left=a.left+this.margins.left;if("right"in a)this.offset.click.left=this.helperProportions.width-a.right+this.margins.left;if("top"in a)this.offset.click.top=a.top+this.margins.top;if("bottom"in a)this.offset.click.top=this.helperProportions.height-a.bottom+this.margins.top},_getParentOffset:function(){this.offsetParent=this.helper.offsetParent();var a=this.offsetParent.offset();if(this.cssPosition=="absolute"&&this.scrollParent[0]!=document&&c.ui.contains(this.scrollParent[0],
this.offsetParent[0])){a.left+=this.scrollParent.scrollLeft();a.top+=this.scrollParent.scrollTop()}if(this.offsetParent[0]==document.body||this.offsetParent[0].tagName&&this.offsetParent[0].tagName.toLowerCase()=="html"&&c.browser.msie)a={top:0,left:0};return{top:a.top+(parseInt(this.offsetParent.css("borderTopWidth"),10)||0),left:a.left+(parseInt(this.offsetParent.css("borderLeftWidth"),10)||0)}},_getRelativeOffset:function(){if(this.cssPosition=="relative"){var a=this.currentItem.position();return{top:a.top-
(parseInt(this.helper.css("top"),10)||0)+this.scrollParent.scrollTop(),left:a.left-(parseInt(this.helper.css("left"),10)||0)+this.scrollParent.scrollLeft()}}else return{top:0,left:0}},_cacheMargins:function(){this.margins={left:parseInt(this.currentItem.css("marginLeft"),10)||0,top:parseInt(this.currentItem.css("marginTop"),10)||0}},_cacheHelperProportions:function(){this.helperProportions={width:this.helper.outerWidth(),height:this.helper.outerHeight()}},_setContainment:function(){var a=this.options;
if(a.containment=="parent")a.containment=this.helper[0].parentNode;if(a.containment=="document"||a.containment=="window")this.containment=[0-this.offset.relative.left-this.offset.parent.left,0-this.offset.relative.top-this.offset.parent.top,c(a.containment=="document"?document:window).width()-this.helperProportions.width-this.margins.left,(c(a.containment=="document"?document:window).height()||document.body.parentNode.scrollHeight)-this.helperProportions.height-this.margins.top];if(!/^(document|window|parent)$/.test(a.containment)){var b=
c(a.containment)[0];a=c(a.containment).offset();var d=c(b).css("overflow")!="hidden";this.containment=[a.left+(parseInt(c(b).css("borderLeftWidth"),10)||0)+(parseInt(c(b).css("paddingLeft"),10)||0)-this.margins.left,a.top+(parseInt(c(b).css("borderTopWidth"),10)||0)+(parseInt(c(b).css("paddingTop"),10)||0)-this.margins.top,a.left+(d?Math.max(b.scrollWidth,b.offsetWidth):b.offsetWidth)-(parseInt(c(b).css("borderLeftWidth"),10)||0)-(parseInt(c(b).css("paddingRight"),10)||0)-this.helperProportions.width-
this.margins.left,a.top+(d?Math.max(b.scrollHeight,b.offsetHeight):b.offsetHeight)-(parseInt(c(b).css("borderTopWidth"),10)||0)-(parseInt(c(b).css("paddingBottom"),10)||0)-this.helperProportions.height-this.margins.top]}},_convertPositionTo:function(a,b){if(!b)b=this.position;var d=a=="absolute"?1:-1,g=this.cssPosition=="absolute"&&!(this.scrollParent[0]!=document&&c.ui.contains(this.scrollParent[0],this.offsetParent[0]))?this.offsetParent:this.scrollParent,f=/(html|body)/i.test(g[0].tagName);return{top:b.top+
this.offset.relative.top*d+this.offset.parent.top*d-(c.browser.safari&&this.cssPosition=="fixed"?0:(this.cssPosition=="fixed"?-this.scrollParent.scrollTop():f?0:g.scrollTop())*d),left:b.left+this.offset.relative.left*d+this.offset.parent.left*d-(c.browser.safari&&this.cssPosition=="fixed"?0:(this.cssPosition=="fixed"?-this.scrollParent.scrollLeft():f?0:g.scrollLeft())*d)}},_generatePosition:function(a){var b=this.options,d=this.cssPosition=="absolute"&&!(this.scrollParent[0]!=document&&c.ui.contains(this.scrollParent[0],
this.offsetParent[0]))?this.offsetParent:this.scrollParent,g=/(html|body)/i.test(d[0].tagName);if(this.cssPosition=="relative"&&!(this.scrollParent[0]!=document&&this.scrollParent[0]!=this.offsetParent[0]))this.offset.relative=this._getRelativeOffset();var f=a.pageX,h=a.pageY;if(this.originalPosition){if(this.containment){if(a.pageX-this.offset.click.left<this.containment[0])f=this.containment[0]+this.offset.click.left;if(a.pageY-this.offset.click.top<this.containment[1])h=this.containment[1]+this.offset.click.top;
if(a.pageX-this.offset.click.left>this.containment[2])f=this.containment[2]+this.offset.click.left;if(a.pageY-this.offset.click.top>this.containment[3])h=this.containment[3]+this.offset.click.top}if(b.grid){h=this.originalPageY+Math.round((h-this.originalPageY)/b.grid[1])*b.grid[1];h=this.containment?!(h-this.offset.click.top<this.containment[1]||h-this.offset.click.top>this.containment[3])?h:!(h-this.offset.click.top<this.containment[1])?h-b.grid[1]:h+b.grid[1]:h;f=this.originalPageX+Math.round((f-
this.originalPageX)/b.grid[0])*b.grid[0];f=this.containment?!(f-this.offset.click.left<this.containment[0]||f-this.offset.click.left>this.containment[2])?f:!(f-this.offset.click.left<this.containment[0])?f-b.grid[0]:f+b.grid[0]:f}}return{top:h-this.offset.click.top-this.offset.relative.top-this.offset.parent.top+(c.browser.safari&&this.cssPosition=="fixed"?0:this.cssPosition=="fixed"?-this.scrollParent.scrollTop():g?0:d.scrollTop()),left:f-this.offset.click.left-this.offset.relative.left-this.offset.parent.left+
(c.browser.safari&&this.cssPosition=="fixed"?0:this.cssPosition=="fixed"?-this.scrollParent.scrollLeft():g?0:d.scrollLeft())}},_rearrange:function(a,b,d,g){d?d[0].appendChild(this.placeholder[0]):b.item[0].parentNode.insertBefore(this.placeholder[0],this.direction=="down"?b.item[0]:b.item[0].nextSibling);this.counter=this.counter?++this.counter:1;var f=this,h=this.counter;window.setTimeout(function(){h==f.counter&&f.refreshPositions(!g)},0)},_clear:function(a,b){this.reverting=false;var d=[];!this._noFinalSort&&
this.currentItem[0].parentNode&&this.placeholder.before(this.currentItem);this._noFinalSort=null;if(this.helper[0]==this.currentItem[0]){for(var g in this._storedCSS)if(this._storedCSS[g]=="auto"||this._storedCSS[g]=="static")this._storedCSS[g]="";this.currentItem.css(this._storedCSS).removeClass("ui-sortable-helper")}else this.currentItem.show();this.fromOutside&&!b&&d.push(function(f){this._trigger("receive",f,this._uiHash(this.fromOutside))});if((this.fromOutside||this.domPosition.prev!=this.currentItem.prev().not(".ui-sortable-helper")[0]||
this.domPosition.parent!=this.currentItem.parent()[0])&&!b)d.push(function(f){this._trigger("update",f,this._uiHash())});if(!c.ui.contains(this.element[0],this.currentItem[0])){b||d.push(function(f){this._trigger("remove",f,this._uiHash())});for(g=this.containers.length-1;g>=0;g--)if(c.ui.contains(this.containers[g].element[0],this.currentItem[0])&&!b){d.push(function(f){return function(h){f._trigger("receive",h,this._uiHash(this))}}.call(this,this.containers[g]));d.push(function(f){return function(h){f._trigger("update",
h,this._uiHash(this))}}.call(this,this.containers[g]))}}for(g=this.containers.length-1;g>=0;g--){b||d.push(function(f){return function(h){f._trigger("deactivate",h,this._uiHash(this))}}.call(this,this.containers[g]));if(this.containers[g].containerCache.over){d.push(function(f){return function(h){f._trigger("out",h,this._uiHash(this))}}.call(this,this.containers[g]));this.containers[g].containerCache.over=0}}this._storedCursor&&c("body").css("cursor",this._storedCursor);this._storedOpacity&&this.helper.css("opacity",
this._storedOpacity);if(this._storedZIndex)this.helper.css("zIndex",this._storedZIndex=="auto"?"":this._storedZIndex);this.dragging=false;if(this.cancelHelperRemoval){if(!b){this._trigger("beforeStop",a,this._uiHash());for(g=0;g<d.length;g++)d[g].call(this,a);this._trigger("stop",a,this._uiHash())}return false}b||this._trigger("beforeStop",a,this._uiHash());this.placeholder[0].parentNode.removeChild(this.placeholder[0]);this.helper[0]!=this.currentItem[0]&&this.helper.remove();this.helper=null;if(!b){for(g=
0;g<d.length;g++)d[g].call(this,a);this._trigger("stop",a,this._uiHash())}this.fromOutside=false;return true},_trigger:function(){c.Widget.prototype._trigger.apply(this,arguments)===false&&this.cancel()},_uiHash:function(a){var b=a||this;return{helper:b.helper,placeholder:b.placeholder||c([]),position:b.position,originalPosition:b.originalPosition,offset:b.positionAbs,item:b.currentItem,sender:a?a.element:null}}});c.extend(c.ui.sortable,{version:"1.8.2"})})(jQuery);
(function(c){c.widget("ui.dialog",{options:{autoOpen:true,buttons:{},closeOnEscape:true,closeText:"close",dialogClass:"",draggable:true,hide:null,height:"auto",maxHeight:false,maxWidth:false,minHeight:150,minWidth:150,modal:false,position:"center",resizable:true,show:null,stack:true,title:"",width:300,zIndex:1E3},_create:function(){this.originalTitle=this.element.attr("title");var a=this,b=a.options,d=b.title||a.originalTitle||"&#160;",g=c.ui.dialog.getTitleId(a.element),f=(a.uiDialog=c("<div></div>")).appendTo(document.body).hide().addClass("ui-dialog ui-widget ui-widget-content ui-corner-all "+
b.dialogClass).css({zIndex:b.zIndex}).attr("tabIndex",-1).css("outline",0).keydown(function(n){if(b.closeOnEscape&&n.keyCode&&n.keyCode===c.ui.keyCode.ESCAPE){a.close(n);n.preventDefault()}}).attr({role:"dialog","aria-labelledby":g}).mousedown(function(n){a.moveToTop(false,n)});a.element.show().removeAttr("title").addClass("ui-dialog-content ui-widget-content").appendTo(f);var h=(a.uiDialogTitlebar=c("<div></div>")).addClass("ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix").prependTo(f),
l=c('<a href="#"></a>').addClass("ui-dialog-titlebar-close ui-corner-all").attr("role","button").hover(function(){l.addClass("ui-state-hover")},function(){l.removeClass("ui-state-hover")}).focus(function(){l.addClass("ui-state-focus")}).blur(function(){l.removeClass("ui-state-focus")}).click(function(n){a.close(n);return false}).appendTo(h);(a.uiDialogTitlebarCloseText=c("<span></span>")).addClass("ui-icon ui-icon-closethick").text(b.closeText).appendTo(l);c("<span></span>").addClass("ui-dialog-title").attr("id",
g).html(d).prependTo(h);if(c.isFunction(b.beforeclose)&&!c.isFunction(b.beforeClose))b.beforeClose=b.beforeclose;h.find("*").add(h).disableSelection();b.draggable&&c.fn.draggable&&a._makeDraggable();b.resizable&&c.fn.resizable&&a._makeResizable();a._createButtons(b.buttons);a._isOpen=false;c.fn.bgiframe&&f.bgiframe()},_init:function(){this.options.autoOpen&&this.open()},destroy:function(){this.overlay&&this.overlay.destroy();this.uiDialog.hide();this.element.unbind(".dialog").removeData("dialog").removeClass("ui-dialog-content ui-widget-content").hide().appendTo("body");
this.uiDialog.remove();this.originalTitle&&this.element.attr("title",this.originalTitle);return this},widget:function(){return this.uiDialog},close:function(a){var b=this,d;if(false!==b._trigger("beforeClose",a)){b.overlay&&b.overlay.destroy();b.uiDialog.unbind("keypress.ui-dialog");b._isOpen=false;if(b.options.hide)b.uiDialog.hide(b.options.hide,function(){b._trigger("close",a)});else{b.uiDialog.hide();b._trigger("close",a)}c.ui.dialog.overlay.resize();if(b.options.modal){d=0;c(".ui-dialog").each(function(){if(this!==
b.uiDialog[0])d=Math.max(d,c(this).css("z-index"))});c.ui.dialog.maxZ=d}return b}},isOpen:function(){return this._isOpen},moveToTop:function(a,b){var d=this.options;if(d.modal&&!a||!d.stack&&!d.modal)return this._trigger("focus",b);if(d.zIndex>c.ui.dialog.maxZ)c.ui.dialog.maxZ=d.zIndex;if(this.overlay){c.ui.dialog.maxZ+=1;this.overlay.$el.css("z-index",c.ui.dialog.overlay.maxZ=c.ui.dialog.maxZ)}d={scrollTop:this.element.attr("scrollTop"),scrollLeft:this.element.attr("scrollLeft")};c.ui.dialog.maxZ+=
1;this.uiDialog.css("z-index",c.ui.dialog.maxZ);this.element.attr(d);this._trigger("focus",b);return this},open:function(){if(!this._isOpen){var a=this.options,b=this.uiDialog;this.overlay=a.modal?new c.ui.dialog.overlay(this):null;b.next().length&&b.appendTo("body");this._size();this._position(a.position);b.show(a.show);this.moveToTop(true);a.modal&&b.bind("keypress.ui-dialog",function(d){if(d.keyCode===c.ui.keyCode.TAB){var g=c(":tabbable",this),f=g.filter(":first");g=g.filter(":last");if(d.target===
g[0]&&!d.shiftKey){f.focus(1);return false}else if(d.target===f[0]&&d.shiftKey){g.focus(1);return false}}});c([]).add(b.find(".ui-dialog-content :tabbable:first")).add(b.find(".ui-dialog-buttonpane :tabbable:first")).add(b).filter(":first").focus();this._trigger("open");this._isOpen=true;return this}},_createButtons:function(a){var b=this,d=false,g=c("<div></div>").addClass("ui-dialog-buttonpane ui-widget-content ui-helper-clearfix");b.uiDialog.find(".ui-dialog-buttonpane").remove();typeof a==="object"&&
a!==null&&c.each(a,function(){return!(d=true)});if(d){c.each(a,function(f,h){var l=c('<button type="button"></button>').text(f).click(function(){h.apply(b.element[0],arguments)}).appendTo(g);c.fn.button&&l.button()});g.appendTo(b.uiDialog)}},_makeDraggable:function(){function a(h){return{position:h.position,offset:h.offset}}var b=this,d=b.options,g=c(document),f;b.uiDialog.draggable({cancel:".ui-dialog-content, .ui-dialog-titlebar-close",handle:".ui-dialog-titlebar",containment:"document",start:function(h,
l){f=d.height==="auto"?"auto":c(this).height();c(this).height(c(this).height()).addClass("ui-dialog-dragging");b._trigger("dragStart",h,a(l))},drag:function(h,l){b._trigger("drag",h,a(l))},stop:function(h,l){d.position=[l.position.left-g.scrollLeft(),l.position.top-g.scrollTop()];c(this).removeClass("ui-dialog-dragging").height(f);b._trigger("dragStop",h,a(l));c.ui.dialog.overlay.resize()}})},_makeResizable:function(a){function b(h){return{originalPosition:h.originalPosition,originalSize:h.originalSize,
position:h.position,size:h.size}}a=a===undefined?this.options.resizable:a;var d=this,g=d.options,f=d.uiDialog.css("position");a=typeof a==="string"?a:"n,e,s,w,se,sw,ne,nw";d.uiDialog.resizable({cancel:".ui-dialog-content",containment:"document",alsoResize:d.element,maxWidth:g.maxWidth,maxHeight:g.maxHeight,minWidth:g.minWidth,minHeight:d._minHeight(),handles:a,start:function(h,l){c(this).addClass("ui-dialog-resizing");d._trigger("resizeStart",h,b(l))},resize:function(h,l){d._trigger("resize",h,b(l))},
stop:function(h,l){c(this).removeClass("ui-dialog-resizing");g.height=c(this).height();g.width=c(this).width();d._trigger("resizeStop",h,b(l));c.ui.dialog.overlay.resize()}}).css("position",f).find(".ui-resizable-se").addClass("ui-icon ui-icon-grip-diagonal-se")},_minHeight:function(){var a=this.options;return a.height==="auto"?a.minHeight:Math.min(a.minHeight,a.height)},_position:function(a){var b=[],d=[0,0];a=a||c.ui.dialog.prototype.options.position;if(typeof a==="string"||typeof a==="object"&&
"0"in a){b=a.split?a.split(" "):[a[0],a[1]];if(b.length===1)b[1]=b[0];c.each(["left","top"],function(g,f){if(+b[g]===b[g]){d[g]=b[g];b[g]=f}})}else if(typeof a==="object"){if("left"in a){b[0]="left";d[0]=a.left}else if("right"in a){b[0]="right";d[0]=-a.right}if("top"in a){b[1]="top";d[1]=a.top}else if("bottom"in a){b[1]="bottom";d[1]=-a.bottom}}(a=this.uiDialog.is(":visible"))||this.uiDialog.show();this.uiDialog.css({top:0,left:0}).position({my:b.join(" "),at:b.join(" "),offset:d.join(" "),of:window,
collision:"fit",using:function(g){var f=c(this).css(g).offset().top;f<0&&c(this).css("top",g.top-f)}});a||this.uiDialog.hide()},_setOption:function(a,b){var d=this.uiDialog,g=d.is(":data(resizable)"),f=false;switch(a){case "beforeclose":a="beforeClose";break;case "buttons":this._createButtons(b);break;case "closeText":this.uiDialogTitlebarCloseText.text(""+b);break;case "dialogClass":d.removeClass(this.options.dialogClass).addClass("ui-dialog ui-widget ui-widget-content ui-corner-all "+b);break;case "disabled":b?
d.addClass("ui-dialog-disabled"):d.removeClass("ui-dialog-disabled");break;case "draggable":b?this._makeDraggable():d.draggable("destroy");break;case "height":f=true;break;case "maxHeight":g&&d.resizable("option","maxHeight",b);f=true;break;case "maxWidth":g&&d.resizable("option","maxWidth",b);f=true;break;case "minHeight":g&&d.resizable("option","minHeight",b);f=true;break;case "minWidth":g&&d.resizable("option","minWidth",b);f=true;break;case "position":this._position(b);break;case "resizable":g&&
!b&&d.resizable("destroy");g&&typeof b==="string"&&d.resizable("option","handles",b);!g&&b!==false&&this._makeResizable(b);break;case "title":c(".ui-dialog-title",this.uiDialogTitlebar).html(""+(b||"&#160;"));break;case "width":f=true;break}c.Widget.prototype._setOption.apply(this,arguments);f&&this._size()},_size:function(){var a=this.options,b;this.element.css({width:"auto",minHeight:0,height:0});b=this.uiDialog.css({height:"auto",width:a.width}).height();this.element.css(a.height==="auto"?{minHeight:Math.max(a.minHeight-
b,0),height:"auto"}:{minHeight:0,height:Math.max(a.height-b,0)}).show();this.uiDialog.is(":data(resizable)")&&this.uiDialog.resizable("option","minHeight",this._minHeight())}});c.extend(c.ui.dialog,{version:"1.8.2",uuid:0,maxZ:0,getTitleId:function(a){a=a.attr("id");if(!a){this.uuid+=1;a=this.uuid}return"ui-dialog-title-"+a},overlay:function(a){this.$el=c.ui.dialog.overlay.create(a)}});c.extend(c.ui.dialog.overlay,{instances:[],oldInstances:[],maxZ:0,events:c.map("focus,mousedown,mouseup,keydown,keypress,click".split(","),
function(a){return a+".dialog-overlay"}).join(" "),create:function(a){if(this.instances.length===0){setTimeout(function(){c.ui.dialog.overlay.instances.length&&c(document).bind(c.ui.dialog.overlay.events,function(d){return c(d.target).zIndex()>=c.ui.dialog.overlay.maxZ})},1);c(document).bind("keydown.dialog-overlay",function(d){if(a.options.closeOnEscape&&d.keyCode&&d.keyCode===c.ui.keyCode.ESCAPE){a.close(d);d.preventDefault()}});c(window).bind("resize.dialog-overlay",c.ui.dialog.overlay.resize)}var b=
(this.oldInstances.pop()||c("<div></div>").addClass("ui-widget-overlay")).appendTo(document.body).css({width:this.width(),height:this.height()});c.fn.bgiframe&&b.bgiframe();this.instances.push(b);return b},destroy:function(a){this.oldInstances.push(this.instances.splice(c.inArray(a,this.instances),1)[0]);this.instances.length===0&&c([document,window]).unbind(".dialog-overlay");a.remove();var b=0;c.each(this.instances,function(){b=Math.max(b,this.css("z-index"))});this.maxZ=b},height:function(){var a,
b;if(c.browser.msie&&c.browser.version<7){a=Math.max(document.documentElement.scrollHeight,document.body.scrollHeight);b=Math.max(document.documentElement.offsetHeight,document.body.offsetHeight);return a<b?c(window).height()+"px":a+"px"}else return c(document).height()+"px"},width:function(){var a,b;if(c.browser.msie&&c.browser.version<7){a=Math.max(document.documentElement.scrollWidth,document.body.scrollWidth);b=Math.max(document.documentElement.offsetWidth,document.body.offsetWidth);return a<
b?c(window).width()+"px":a+"px"}else return c(document).width()+"px"},resize:function(){var a=c([]);c.each(c.ui.dialog.overlay.instances,function(){a=a.add(this)});a.css({width:0,height:0}).css({width:c.ui.dialog.overlay.width(),height:c.ui.dialog.overlay.height()})}});c.extend(c.ui.dialog.overlay.prototype,{destroy:function(){c.ui.dialog.overlay.destroy(this.$el)}})})(jQuery);
jQuery.effects||function(c){function a(j){var e;if(j&&j.constructor==Array&&j.length==3)return j;if(e=/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/.exec(j))return[parseInt(e[1],10),parseInt(e[2],10),parseInt(e[3],10)];if(e=/rgb\(\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*\)/.exec(j))return[parseFloat(e[1])*2.55,parseFloat(e[2])*2.55,parseFloat(e[3])*2.55];if(e=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/.exec(j))return[parseInt(e[1],
16),parseInt(e[2],16),parseInt(e[3],16)];if(e=/#([a-fA-F0-9])([a-fA-F0-9])([a-fA-F0-9])/.exec(j))return[parseInt(e[1]+e[1],16),parseInt(e[2]+e[2],16),parseInt(e[3]+e[3],16)];if(/rgba\(0, 0, 0, 0\)/.exec(j))return h.transparent;return h[c.trim(j).toLowerCase()]}function b(){var j=document.defaultView?document.defaultView.getComputedStyle(this,null):this.currentStyle,e={},i,k;if(j&&j.length&&j[0]&&j[j[0]])for(var m=j.length;m--;){i=j[m];if(typeof j[i]=="string"){k=i.replace(/\-(\w)/g,function(o,p){return p.toUpperCase()});
e[k]=j[i]}}else for(i in j)if(typeof j[i]==="string")e[i]=j[i];return e}function d(j){var e,i;for(e in j){i=j[e];if(i==null||c.isFunction(i)||e in n||/scrollbar/.test(e)||!/color/i.test(e)&&isNaN(parseFloat(i)))delete j[e]}return j}function g(j,e){var i={_:0},k;for(k in e)if(j[k]!=e[k])i[k]=e[k];return i}function f(j,e,i,k){if(typeof j=="object"){k=e;i=null;e=j;j=e.effect}if(c.isFunction(e)){k=e;i=null;e={}}if(c.isFunction(i)){k=i;i=null}if(typeof e=="number"||c.fx.speeds[e]){k=i;i=e;e={}}e=e||{};
i=i||e.duration;i=c.fx.off?0:typeof i=="number"?i:c.fx.speeds[i]||c.fx.speeds._default;k=k||e.complete;return[j,e,i,k]}c.effects={};c.each(["backgroundColor","borderBottomColor","borderLeftColor","borderRightColor","borderTopColor","color","outlineColor"],function(j,e){c.fx.step[e]=function(i){if(!i.colorInit){var k;k=i.elem;var m=e,o;do{o=c.curCSS(k,m);if(o!=""&&o!="transparent"||c.nodeName(k,"body"))break;m="backgroundColor"}while(k=k.parentNode);k=a(o);i.start=k;i.end=a(i.end);i.colorInit=true}i.elem.style[e]=
"rgb("+Math.max(Math.min(parseInt(i.pos*(i.end[0]-i.start[0])+i.start[0],10),255),0)+","+Math.max(Math.min(parseInt(i.pos*(i.end[1]-i.start[1])+i.start[1],10),255),0)+","+Math.max(Math.min(parseInt(i.pos*(i.end[2]-i.start[2])+i.start[2],10),255),0)+")"}});var h={aqua:[0,255,255],azure:[240,255,255],beige:[245,245,220],black:[0,0,0],blue:[0,0,255],brown:[165,42,42],cyan:[0,255,255],darkblue:[0,0,139],darkcyan:[0,139,139],darkgrey:[169,169,169],darkgreen:[0,100,0],darkkhaki:[189,183,107],darkmagenta:[139,
0,139],darkolivegreen:[85,107,47],darkorange:[255,140,0],darkorchid:[153,50,204],darkred:[139,0,0],darksalmon:[233,150,122],darkviolet:[148,0,211],fuchsia:[255,0,255],gold:[255,215,0],green:[0,128,0],indigo:[75,0,130],khaki:[240,230,140],lightblue:[173,216,230],lightcyan:[224,255,255],lightgreen:[144,238,144],lightgrey:[211,211,211],lightpink:[255,182,193],lightyellow:[255,255,224],lime:[0,255,0],magenta:[255,0,255],maroon:[128,0,0],navy:[0,0,128],olive:[128,128,0],orange:[255,165,0],pink:[255,192,
203],purple:[128,0,128],violet:[128,0,128],red:[255,0,0],silver:[192,192,192],white:[255,255,255],yellow:[255,255,0],transparent:[255,255,255]},l=["add","remove","toggle"],n={border:1,borderBottom:1,borderColor:1,borderLeft:1,borderRight:1,borderTop:1,borderWidth:1,margin:1,padding:1};c.effects.animateClass=function(j,e,i,k){if(c.isFunction(i)){k=i;i=null}return this.each(function(){var m=c(this),o=m.attr("style")||" ",p=d(b.call(this)),q,r=m.attr("className");c.each(l,function(t,s){j[s]&&m[s+"Class"](j[s])});
q=d(b.call(this));m.attr("className",r);m.animate(g(p,q),e,i,function(){c.each(l,function(t,s){j[s]&&m[s+"Class"](j[s])});if(typeof m.attr("style")=="object"){m.attr("style").cssText="";m.attr("style").cssText=o}else m.attr("style",o);k&&k.apply(this,arguments)})})};c.fn.extend({_addClass:c.fn.addClass,addClass:function(j,e,i,k){return e?c.effects.animateClass.apply(this,[{add:j},e,i,k]):this._addClass(j)},_removeClass:c.fn.removeClass,removeClass:function(j,e,i,k){return e?c.effects.animateClass.apply(this,
[{remove:j},e,i,k]):this._removeClass(j)},_toggleClass:c.fn.toggleClass,toggleClass:function(j,e,i,k,m){return typeof e=="boolean"||e===undefined?i?c.effects.animateClass.apply(this,[e?{add:j}:{remove:j},i,k,m]):this._toggleClass(j,e):c.effects.animateClass.apply(this,[{toggle:j},e,i,k])},switchClass:function(j,e,i,k,m){return c.effects.animateClass.apply(this,[{add:e,remove:j},i,k,m])}});c.extend(c.effects,{version:"1.8.2",save:function(j,e){for(var i=0;i<e.length;i++)e[i]!==null&&j.data("ec.storage."+
e[i],j[0].style[e[i]])},restore:function(j,e){for(var i=0;i<e.length;i++)e[i]!==null&&j.css(e[i],j.data("ec.storage."+e[i]))},setMode:function(j,e){if(e=="toggle")e=j.is(":hidden")?"show":"hide";return e},getBaseline:function(j,e){var i,k;switch(j[0]){case "top":i=0;break;case "middle":i=0.5;break;case "bottom":i=1;break;default:i=j[0]/e.height}switch(j[1]){case "left":k=0;break;case "center":k=0.5;break;case "right":k=1;break;default:k=j[1]/e.width}return{x:k,y:i}},createWrapper:function(j){if(j.parent().is(".ui-effects-wrapper"))return j.parent();
var e={width:j.outerWidth(true),height:j.outerHeight(true),"float":j.css("float")},i=c("<div></div>").addClass("ui-effects-wrapper").css({fontSize:"100%",background:"transparent",border:"none",margin:0,padding:0});j.wrap(i);i=j.parent();if(j.css("position")=="static"){i.css({position:"relative"});j.css({position:"relative"})}else{c.extend(e,{position:j.css("position"),zIndex:j.css("z-index")});c.each(["top","left","bottom","right"],function(k,m){e[m]=j.css(m);if(isNaN(parseInt(e[m],10)))e[m]="auto"});
j.css({position:"relative",top:0,left:0})}return i.css(e).show()},removeWrapper:function(j){if(j.parent().is(".ui-effects-wrapper"))return j.parent().replaceWith(j);return j},setTransition:function(j,e,i,k){k=k||{};c.each(e,function(m,o){unit=j.cssUnit(o);if(unit[0]>0)k[o]=unit[0]*i+unit[1]});return k}});c.fn.extend({effect:function(j){var e=f.apply(this,arguments);e={options:e[1],duration:e[2],callback:e[3]};var i=c.effects[j];return i&&!c.fx.off?i.call(this,e):this},_show:c.fn.show,show:function(j){if(!j||
typeof j=="number"||c.fx.speeds[j])return this._show.apply(this,arguments);else{var e=f.apply(this,arguments);e[1].mode="show";return this.effect.apply(this,e)}},_hide:c.fn.hide,hide:function(j){if(!j||typeof j=="number"||c.fx.speeds[j])return this._hide.apply(this,arguments);else{var e=f.apply(this,arguments);e[1].mode="hide";return this.effect.apply(this,e)}},__toggle:c.fn.toggle,toggle:function(j){if(!j||typeof j=="number"||c.fx.speeds[j]||typeof j=="boolean"||c.isFunction(j))return this.__toggle.apply(this,
arguments);else{var e=f.apply(this,arguments);e[1].mode="toggle";return this.effect.apply(this,e)}},cssUnit:function(j){var e=this.css(j),i=[];c.each(["em","px","%","pt"],function(k,m){if(e.indexOf(m)>0)i=[parseFloat(e),m]});return i}});c.easing.jswing=c.easing.swing;c.extend(c.easing,{def:"easeOutQuad",swing:function(j,e,i,k,m){return c.easing[c.easing.def](j,e,i,k,m)},easeInQuad:function(j,e,i,k,m){return k*(e/=m)*e+i},easeOutQuad:function(j,e,i,k,m){return-k*(e/=m)*(e-2)+i},easeInOutQuad:function(j,
e,i,k,m){if((e/=m/2)<1)return k/2*e*e+i;return-k/2*(--e*(e-2)-1)+i},easeInCubic:function(j,e,i,k,m){return k*(e/=m)*e*e+i},easeOutCubic:function(j,e,i,k,m){return k*((e=e/m-1)*e*e+1)+i},easeInOutCubic:function(j,e,i,k,m){if((e/=m/2)<1)return k/2*e*e*e+i;return k/2*((e-=2)*e*e+2)+i},easeInQuart:function(j,e,i,k,m){return k*(e/=m)*e*e*e+i},easeOutQuart:function(j,e,i,k,m){return-k*((e=e/m-1)*e*e*e-1)+i},easeInOutQuart:function(j,e,i,k,m){if((e/=m/2)<1)return k/2*e*e*e*e+i;return-k/2*((e-=2)*e*e*e-2)+
i},easeInQuint:function(j,e,i,k,m){return k*(e/=m)*e*e*e*e+i},easeOutQuint:function(j,e,i,k,m){return k*((e=e/m-1)*e*e*e*e+1)+i},easeInOutQuint:function(j,e,i,k,m){if((e/=m/2)<1)return k/2*e*e*e*e*e+i;return k/2*((e-=2)*e*e*e*e+2)+i},easeInSine:function(j,e,i,k,m){return-k*Math.cos(e/m*(Math.PI/2))+k+i},easeOutSine:function(j,e,i,k,m){return k*Math.sin(e/m*(Math.PI/2))+i},easeInOutSine:function(j,e,i,k,m){return-k/2*(Math.cos(Math.PI*e/m)-1)+i},easeInExpo:function(j,e,i,k,m){return e==0?i:k*Math.pow(2,
10*(e/m-1))+i},easeOutExpo:function(j,e,i,k,m){return e==m?i+k:k*(-Math.pow(2,-10*e/m)+1)+i},easeInOutExpo:function(j,e,i,k,m){if(e==0)return i;if(e==m)return i+k;if((e/=m/2)<1)return k/2*Math.pow(2,10*(e-1))+i;return k/2*(-Math.pow(2,-10*--e)+2)+i},easeInCirc:function(j,e,i,k,m){return-k*(Math.sqrt(1-(e/=m)*e)-1)+i},easeOutCirc:function(j,e,i,k,m){return k*Math.sqrt(1-(e=e/m-1)*e)+i},easeInOutCirc:function(j,e,i,k,m){if((e/=m/2)<1)return-k/2*(Math.sqrt(1-e*e)-1)+i;return k/2*(Math.sqrt(1-(e-=2)*
e)+1)+i},easeInElastic:function(j,e,i,k,m){j=1.70158;var o=0,p=k;if(e==0)return i;if((e/=m)==1)return i+k;o||(o=m*0.3);if(p<Math.abs(k)){p=k;j=o/4}else j=o/(2*Math.PI)*Math.asin(k/p);return-(p*Math.pow(2,10*(e-=1))*Math.sin((e*m-j)*2*Math.PI/o))+i},easeOutElastic:function(j,e,i,k,m){j=1.70158;var o=0,p=k;if(e==0)return i;if((e/=m)==1)return i+k;o||(o=m*0.3);if(p<Math.abs(k)){p=k;j=o/4}else j=o/(2*Math.PI)*Math.asin(k/p);return p*Math.pow(2,-10*e)*Math.sin((e*m-j)*2*Math.PI/o)+k+i},easeInOutElastic:function(j,
e,i,k,m){j=1.70158;var o=0,p=k;if(e==0)return i;if((e/=m/2)==2)return i+k;o||(o=m*0.3*1.5);if(p<Math.abs(k)){p=k;j=o/4}else j=o/(2*Math.PI)*Math.asin(k/p);if(e<1)return-0.5*p*Math.pow(2,10*(e-=1))*Math.sin((e*m-j)*2*Math.PI/o)+i;return p*Math.pow(2,-10*(e-=1))*Math.sin((e*m-j)*2*Math.PI/o)*0.5+k+i},easeInBack:function(j,e,i,k,m,o){if(o==undefined)o=1.70158;return k*(e/=m)*e*((o+1)*e-o)+i},easeOutBack:function(j,e,i,k,m,o){if(o==undefined)o=1.70158;return k*((e=e/m-1)*e*((o+1)*e+o)+1)+i},easeInOutBack:function(j,
e,i,k,m,o){if(o==undefined)o=1.70158;if((e/=m/2)<1)return k/2*e*e*(((o*=1.525)+1)*e-o)+i;return k/2*((e-=2)*e*(((o*=1.525)+1)*e+o)+2)+i},easeInBounce:function(j,e,i,k,m){return k-c.easing.easeOutBounce(j,m-e,0,k,m)+i},easeOutBounce:function(j,e,i,k,m){return(e/=m)<1/2.75?k*7.5625*e*e+i:e<2/2.75?k*(7.5625*(e-=1.5/2.75)*e+0.75)+i:e<2.5/2.75?k*(7.5625*(e-=2.25/2.75)*e+0.9375)+i:k*(7.5625*(e-=2.625/2.75)*e+0.984375)+i},easeInOutBounce:function(j,e,i,k,m){if(e<m/2)return c.easing.easeInBounce(j,e*2,0,
k,m)*0.5+i;return c.easing.easeOutBounce(j,e*2-m,0,k,m)*0.5+k*0.5+i}})}(jQuery);
(function(c){c.effects.blind=function(a){return this.queue(function(){var b=c(this),d=["position","top","left"],g=c.effects.setMode(b,a.options.mode||"hide"),f=a.options.direction||"vertical";c.effects.save(b,d);b.show();var h=c.effects.createWrapper(b).css({overflow:"hidden"}),l=f=="vertical"?"height":"width";f=f=="vertical"?h.height():h.width();g=="show"&&h.css(l,0);var n={};n[l]=g=="show"?f:0;h.animate(n,a.duration,a.options.easing,function(){g=="hide"&&b.hide();c.effects.restore(b,d);c.effects.removeWrapper(b);
a.callback&&a.callback.apply(b[0],arguments);b.dequeue()})})}})(jQuery);
(function(c){c.effects.bounce=function(a){return this.queue(function(){var b=c(this),d=["position","top","left"],g=c.effects.setMode(b,a.options.mode||"effect"),f=a.options.direction||"up",h=a.options.distance||20,l=a.options.times||5,n=a.duration||250;/show|hide/.test(g)&&d.push("opacity");c.effects.save(b,d);b.show();c.effects.createWrapper(b);var j=f=="up"||f=="down"?"top":"left";f=f=="up"||f=="left"?"pos":"neg";h=a.options.distance||(j=="top"?b.outerHeight({margin:true})/3:b.outerWidth({margin:true})/
3);if(g=="show")b.css("opacity",0).css(j,f=="pos"?-h:h);if(g=="hide")h/=l*2;g!="hide"&&l--;if(g=="show"){var e={opacity:1};e[j]=(f=="pos"?"+=":"-=")+h;b.animate(e,n/2,a.options.easing);h/=2;l--}for(e=0;e<l;e++){var i={},k={};i[j]=(f=="pos"?"-=":"+=")+h;k[j]=(f=="pos"?"+=":"-=")+h;b.animate(i,n/2,a.options.easing).animate(k,n/2,a.options.easing);h=g=="hide"?h*2:h/2}if(g=="hide"){e={opacity:0};e[j]=(f=="pos"?"-=":"+=")+h;b.animate(e,n/2,a.options.easing,function(){b.hide();c.effects.restore(b,d);c.effects.removeWrapper(b);
a.callback&&a.callback.apply(this,arguments)})}else{i={};k={};i[j]=(f=="pos"?"-=":"+=")+h;k[j]=(f=="pos"?"+=":"-=")+h;b.animate(i,n/2,a.options.easing).animate(k,n/2,a.options.easing,function(){c.effects.restore(b,d);c.effects.removeWrapper(b);a.callback&&a.callback.apply(this,arguments)})}b.queue("fx",function(){b.dequeue()});b.dequeue()})}})(jQuery);
(function(c){c.effects.drop=function(a){return this.queue(function(){var b=c(this),d=["position","top","left","opacity"],g=c.effects.setMode(b,a.options.mode||"hide"),f=a.options.direction||"left";c.effects.save(b,d);b.show();c.effects.createWrapper(b);var h=f=="up"||f=="down"?"top":"left";f=f=="up"||f=="left"?"pos":"neg";var l=a.options.distance||(h=="top"?b.outerHeight({margin:true})/2:b.outerWidth({margin:true})/2);if(g=="show")b.css("opacity",0).css(h,f=="pos"?-l:l);var n={opacity:g=="show"?1:
0};n[h]=(g=="show"?f=="pos"?"+=":"-=":f=="pos"?"-=":"+=")+l;b.animate(n,{queue:false,duration:a.duration,easing:a.options.easing,complete:function(){g=="hide"&&b.hide();c.effects.restore(b,d);c.effects.removeWrapper(b);a.callback&&a.callback.apply(this,arguments);b.dequeue()}})})}})(jQuery);
(function(c){c.effects.highlight=function(a){return this.queue(function(){var b=c(this),d=["backgroundImage","backgroundColor","opacity"],g=c.effects.setMode(b,a.options.mode||"show"),f={backgroundColor:b.css("backgroundColor")};if(g=="hide")f.opacity=0;c.effects.save(b,d);b.show().css({backgroundImage:"none",backgroundColor:a.options.color||"#ffff99"}).animate(f,{queue:false,duration:a.duration,easing:a.options.easing,complete:function(){g=="hide"&&b.hide();c.effects.restore(b,d);g=="show"&&!c.support.opacity&&
this.style.removeAttribute("filter");a.callback&&a.callback.apply(this,arguments);b.dequeue()}})})}})(jQuery);
(function(c){c.effects.pulsate=function(a){return this.queue(function(){var b=c(this),d=c.effects.setMode(b,a.options.mode||"show");times=(a.options.times||5)*2-1;duration=a.duration?a.duration/2:c.fx.speeds._default/2;isVisible=b.is(":visible");animateTo=0;if(!isVisible){b.css("opacity",0).show();animateTo=1}if(d=="hide"&&isVisible||d=="show"&&!isVisible)times--;for(d=0;d<times;d++){b.animate({opacity:animateTo},duration,a.options.easing);animateTo=(animateTo+1)%2}b.animate({opacity:animateTo},duration,
a.options.easing,function(){animateTo==0&&b.hide();a.callback&&a.callback.apply(this,arguments)});b.queue("fx",function(){b.dequeue()}).dequeue()})}})(jQuery);
(function(c){c.effects.puff=function(a){return this.queue(function(){var b=c(this),d=c.effects.setMode(b,a.options.mode||"hide"),g=parseInt(a.options.percent,10)||150,f=g/100,h={height:b.height(),width:b.width()};c.extend(a.options,{fade:true,mode:d,percent:d=="hide"?g:100,from:d=="hide"?h:{height:h.height*f,width:h.width*f}});b.effect("scale",a.options,a.duration,a.callback);b.dequeue()})};c.effects.scale=function(a){return this.queue(function(){var b=c(this),d=c.extend(true,{},a.options),g=c.effects.setMode(b,
a.options.mode||"effect"),f=parseInt(a.options.percent,10)||(parseInt(a.options.percent,10)==0?0:g=="hide"?0:100),h=a.options.direction||"both",l=a.options.origin;if(g!="effect"){d.origin=l||["middle","center"];d.restore=true}l={height:b.height(),width:b.width()};b.from=a.options.from||(g=="show"?{height:0,width:0}:l);f={y:h!="horizontal"?f/100:1,x:h!="vertical"?f/100:1};b.to={height:l.height*f.y,width:l.width*f.x};if(a.options.fade){if(g=="show"){b.from.opacity=0;b.to.opacity=1}if(g=="hide"){b.from.opacity=
1;b.to.opacity=0}}d.from=b.from;d.to=b.to;d.mode=g;b.effect("size",d,a.duration,a.callback);b.dequeue()})};c.effects.size=function(a){return this.queue(function(){var b=c(this),d=["position","top","left","width","height","overflow","opacity"],g=["position","top","left","overflow","opacity"],f=["width","height","overflow"],h=["fontSize"],l=["borderTopWidth","borderBottomWidth","paddingTop","paddingBottom"],n=["borderLeftWidth","borderRightWidth","paddingLeft","paddingRight"],j=c.effects.setMode(b,
a.options.mode||"effect"),e=a.options.restore||false,i=a.options.scale||"both",k=a.options.origin,m={height:b.height(),width:b.width()};b.from=a.options.from||m;b.to=a.options.to||m;if(k){k=c.effects.getBaseline(k,m);b.from.top=(m.height-b.from.height)*k.y;b.from.left=(m.width-b.from.width)*k.x;b.to.top=(m.height-b.to.height)*k.y;b.to.left=(m.width-b.to.width)*k.x}var o={from:{y:b.from.height/m.height,x:b.from.width/m.width},to:{y:b.to.height/m.height,x:b.to.width/m.width}};if(i=="box"||i=="both"){if(o.from.y!=
o.to.y){d=d.concat(l);b.from=c.effects.setTransition(b,l,o.from.y,b.from);b.to=c.effects.setTransition(b,l,o.to.y,b.to)}if(o.from.x!=o.to.x){d=d.concat(n);b.from=c.effects.setTransition(b,n,o.from.x,b.from);b.to=c.effects.setTransition(b,n,o.to.x,b.to)}}if(i=="content"||i=="both")if(o.from.y!=o.to.y){d=d.concat(h);b.from=c.effects.setTransition(b,h,o.from.y,b.from);b.to=c.effects.setTransition(b,h,o.to.y,b.to)}c.effects.save(b,e?d:g);b.show();c.effects.createWrapper(b);b.css("overflow","hidden").css(b.from);
if(i=="content"||i=="both"){l=l.concat(["marginTop","marginBottom"]).concat(h);n=n.concat(["marginLeft","marginRight"]);f=d.concat(l).concat(n);b.find("*[width]").each(function(){child=c(this);e&&c.effects.save(child,f);var p={height:child.height(),width:child.width()};child.from={height:p.height*o.from.y,width:p.width*o.from.x};child.to={height:p.height*o.to.y,width:p.width*o.to.x};if(o.from.y!=o.to.y){child.from=c.effects.setTransition(child,l,o.from.y,child.from);child.to=c.effects.setTransition(child,
l,o.to.y,child.to)}if(o.from.x!=o.to.x){child.from=c.effects.setTransition(child,n,o.from.x,child.from);child.to=c.effects.setTransition(child,n,o.to.x,child.to)}child.css(child.from);child.animate(child.to,a.duration,a.options.easing,function(){e&&c.effects.restore(child,f)})})}b.animate(b.to,{queue:false,duration:a.duration,easing:a.options.easing,complete:function(){b.to.opacity===0&&b.css("opacity",b.from.opacity);j=="hide"&&b.hide();c.effects.restore(b,e?d:g);c.effects.removeWrapper(b);a.callback&&
a.callback.apply(this,arguments);b.dequeue()}})})}})(jQuery);
(function(c){c.effects.slide=function(a){return this.queue(function(){var b=c(this),d=["position","top","left"],g=c.effects.setMode(b,a.options.mode||"show"),f=a.options.direction||"left";c.effects.save(b,d);b.show();c.effects.createWrapper(b).css({overflow:"hidden"});var h=f=="up"||f=="down"?"top":"left";f=f=="up"||f=="left"?"pos":"neg";var l=a.options.distance||(h=="top"?b.outerHeight({margin:true}):b.outerWidth({margin:true}));if(g=="show")b.css(h,f=="pos"?-l:l);var n={};n[h]=(g=="show"?f=="pos"?
"+=":"-=":f=="pos"?"-=":"+=")+l;b.animate(n,{queue:false,duration:a.duration,easing:a.options.easing,complete:function(){g=="hide"&&b.hide();c.effects.restore(b,d);c.effects.removeWrapper(b);a.callback&&a.callback.apply(this,arguments);b.dequeue()}})})}})(jQuery);
